import { Matrix4, Vector3 } from 'three'
import type { IfcAPI } from 'web-ifc'
import type { PlanBounds, Riser, Storey, StoreyId } from '@/domain/types'

type IfcHandle = { type: 5; value: number }
type IfcWritableLine = { expressID: number; type: number; [key: string]: unknown }
type IfcEntityRef = { expressID: number; type: number }
type ImportedIfcTypes = Awaited<typeof import('web-ifc')>
type Point3Debug = { x: number; y: number; z: number }
type RiserStoreyDebugInfo = Pick<Storey, 'id' | 'name' | 'elevation'>
type StoreyContext = {
  storeyId: StoreyId
  targetStoreyPlacementId: number
  ownerHistory: IfcHandle | null
  containment: {
    expressID: number
    type: number
    RelatedElements?: unknown[]
    RelatingStructure?: IfcHandle | null
  } | null
}
type ResolvedRiserPlacement = {
  webPositionUsedForExport: Point3Debug
  worldOrModelPosition: Point3Debug
  finalIfcLocalPlacement: Point3Debug
  parentPlacementOrigin: Point3Debug
  parentPlacementAxis: Point3Debug
  parentPlacementRefDirection: Point3Debug
}
type WrittenRiser = {
  element: IfcEntityRef
  createdEntityIds: Record<string, number | undefined>
  createdRelationIds: Record<string, number | undefined>
}
type StoreySpanInfo = {
  id: StoreyId
  name: string | null
  elevation: number | null
}
type StackGroup = {
  stackId: string
  stackLabel: string
  canonicalPosition: { x: number; y: number; z: number }
  bottomRiser: Riser
  topRiser: Riser
  members: Riser[]
}

export type FullIfcRiserDebugOptions = {
  exportRunId?: string
  timestamp?: string
  sourceIfcName?: string | null
  storeys?: RiserStoreyDebugInfo[]
}

export type FullIfcRiserDebugRecord = {
  exportRunId: string
  timestamp: string
  sourceIfcName: string | null
  schema: string
  riserId: string
  riserTag: string
  floorId: StoreyId
  floorName: string | null
  storeyEntityId: StoreyId
  storeyName: string | null
  storeyElevation: number | null
  webPositionRaw: Point3Debug
  webPositionUsedForExport: Point3Debug
  floorLocalPosition: Point3Debug
  worldOrModelPosition: Point3Debug
  chosenAnchorEntityId: number
  chosenAnchorType: string
  chosenParentPlacementId: number
  parentPlacementOrigin: Point3Debug
  parentPlacementAxis: Point3Debug
  parentPlacementRefDirection: Point3Debug
  finalIfcLocalPlacement: Point3Debug
  bottomStoreyEntityId: StoreyId
  bottomStoreyName: string | null
  bottomStoreyElevation: number | null
  topStoreyEntityId: StoreyId
  topStoreyName: string | null
  topStoreyElevation: number | null
  coveredStoreyIds: StoreyId[]
  extrusionLengthSourceUnits: number
  createdEntityIds: Record<string, number>
  createdRelationIds: Record<string, number>
  warnings: string[]
  notes: string[]
}

export type FullIfcSystemAssignmentDebug = {
  ifcSystemId: number
  ifcRelAssignsToGroupId: number
  ifcRelServicesBuildingsId: number
  ifcBuildingId: number
  name: string
  objectType: string
  description: string
}

export type FullIfcRiserDebugArtifact = {
  exportRunId: string
  timestamp: string
  sourceIfcName: string | null
  schema: string
  sourceFloorPlanBounds: PlanBounds | null
  systemAssignment: FullIfcSystemAssignmentDebug | null
  risers: FullIfcRiserDebugRecord[]
  warnings: string[]
  notes: string[]
}

export type FullIfcWithRisersDebugResult = {
  ifcBytes: Uint8Array
  debugMapping: FullIfcRiserDebugArtifact
}

const RISER_OUTER_DIAMETER_MM = 110
const RISER_INNER_DIAMETER_MM = 100
const RISER_WALL_THICKNESS_MM = 5
const RISER_ROUGHNESS_MM = 0.0015
const RISER_PIPE_TYPE_NAME = 'BIMPipe PVC 110'
const RISER_SYSTEM_NAME = 'BIMPipe Sanitary Stacks'
const RISER_SYSTEM_DESCRIPTION = 'Sanitary drainage system generated by BIMPipe.'
const RISER_MATERIAL_NAME = 'PVC'
const RISER_STACK_ALIGNMENT_EPSILON = 1e-3

/** sourceFloorPlanBounds is preserved only as debug artifact metadata; it is not used for placement. */
export async function exportFullIfcWithRisers(
  api: IfcAPI,
  sourceBytes: Uint8Array,
  primaryStoreyId: StoreyId,
  risers: Riser[],
  sourceFloorPlanBounds: PlanBounds | null = null,
): Promise<Uint8Array> {
  const { ifcBytes } = await exportFullIfcWithRisersInternal(
    api,
    sourceBytes,
    primaryStoreyId,
    risers,
    sourceFloorPlanBounds,
    null,
  )
  return ifcBytes
}

/** sourceFloorPlanBounds is preserved only as debug artifact metadata; it is not used for placement. */
export async function exportFullIfcWithRisersWithDebug(
  api: IfcAPI,
  sourceBytes: Uint8Array,
  primaryStoreyId: StoreyId,
  risers: Riser[],
  sourceFloorPlanBounds: PlanBounds | null = null,
  debugOptions: FullIfcRiserDebugOptions = {},
): Promise<FullIfcWithRisersDebugResult> {
  const result = await exportFullIfcWithRisersInternal(
    api,
    sourceBytes,
    primaryStoreyId,
    risers,
    sourceFloorPlanBounds,
    debugOptions,
  )
  if (!result.debugMapping) {
    throw new Error('Debug mapping was not created.')
  }
  return {
    ifcBytes: result.ifcBytes,
    debugMapping: result.debugMapping,
  }
}

async function exportFullIfcWithRisersInternal(
  api: IfcAPI,
  sourceBytes: Uint8Array,
  _primaryStoreyId: StoreyId,
  risers: Riser[],
  sourceFloorPlanBounds: PlanBounds | null,
  debugOptions: FullIfcRiserDebugOptions | null,
): Promise<{
  ifcBytes: Uint8Array
  debugMapping: FullIfcRiserDebugArtifact | null
}> {
  if (risers.length === 0) {
    throw new Error('Add or suggest risers before downloading the full IFC.')
  }

  const ifc = await import('web-ifc')
  const { IFCRELCONTAINEDINSPATIALSTRUCTURE, IFCLABEL } = ifc

  const modelId = api.OpenModel(sourceBytes.slice())

  try {
    const schema = api.GetModelSchema(modelId)
    const bodyContextId = resolveBodyContext(api, modelId)
    const millimetresPerSourceUnit = resolveLengthScaleToMillimetres(api, modelId)
    const sourceUnitsPerViewerUnit = 1000 / millimetresPerSourceUnit
    const riserRadiusSourceUnits = (RISER_OUTER_DIAMETER_MM / 2) / millimetresPerSourceUnit
    const debugMapping = debugOptions
      ? createDebugArtifact(debugOptions, schema, sourceFloorPlanBounds)
      : null
    const debugStoreysById = new Map(
      (debugOptions?.storeys ?? []).map((storey) => [storey.id, storey]),
    )
    const storeysById = buildRiserStoreysById(api, modelId, risers, debugStoreysById)
    const stackGroups = groupRisersByStackId(risers, storeysById)
    const createdFlowSegmentHandles: IfcHandle[] = []
    let systemOwnerHistory: IfcHandle | null = null

    for (const stack of stackGroups) {
      const bottomStoreyId = stack.bottomRiser.storeyId
      const storeyContext = resolveStoreyContext(
        api,
        modelId,
        bottomStoreyId,
        IFCRELCONTAINEDINSPATIALSTRUCTURE,
      )
      const placement = resolveRiserPlacement(
        api,
        modelId,
        storeyContext,
        stack.bottomRiser,
        sourceUnitsPerViewerUnit,
      )
      const bottomElevation = getStoreyElevation(stack.bottomRiser, storeysById)
      const topElevation = getStoreyElevation(stack.topRiser, storeysById)
      const extrusionLengthSourceUnits = topElevation - bottomElevation
      if (!Number.isFinite(extrusionLengthSourceUnits) || extrusionLengthSourceUnits <= 0) {
        throw new Error(
          `Riser stack ${stack.stackLabel} resolved a non-positive extrusion length (${extrusionLengthSourceUnits}); ` +
          `bottom storey ${stack.bottomRiser.storeyId}, top storey ${stack.topRiser.storeyId}.`,
        )
      }

      const riserElement = writeMinimalRiser(
        api,
        ifc,
        modelId,
        schema,
        bodyContextId,
        storeyContext.targetStoreyPlacementId,
        storeyContext.ownerHistory,
        stack.bottomRiser,
        new Vector3(
          placement.finalIfcLocalPlacement.x,
          placement.finalIfcLocalPlacement.y,
          placement.finalIfcLocalPlacement.z,
        ),
        riserRadiusSourceUnits,
        extrusionLengthSourceUnits,
        millimetresPerSourceUnit,
      )
      const createdHandles = [handleRef(riserElement.element.expressID)]
      createdFlowSegmentHandles.push(...createdHandles)
      systemOwnerHistory ??= storeyContext.ownerHistory

      const debugRecord = debugMapping
        ? buildRiserDebugRecord(
            api,
            modelId,
            debugMapping,
            schema,
            storeyContext,
            storeysById,
            stack,
            placement,
            riserElement,
            extrusionLengthSourceUnits,
          )
        : null
      if (debugMapping && debugRecord) {
        debugMapping.risers.push(debugRecord)
      }

      if (storeyContext.containment) {
        storeyContext.containment.RelatedElements = [
          ...(Array.isArray(storeyContext.containment.RelatedElements) ? storeyContext.containment.RelatedElements : []),
          ...createdHandles,
        ]
        api.WriteLine(modelId, storeyContext.containment)
        if (debugRecord) {
          debugRecord.notes.push(`Appended to existing IfcRelContainedInSpatialStructure #${storeyContext.containment.expressID}.`)
        }
      } else {
        const relation = api.CreateIfcEntity(
          modelId,
          IFCRELCONTAINEDINSPATIALSTRUCTURE,
          api.CreateIFCGloballyUniqueId(modelId),
          storeyContext.ownerHistory,
          api.CreateIfcType(modelId, IFCLABEL, 'BIMPipe riser set'),
          null,
          createdHandles,
          handleRef(bottomStoreyId),
        )
        api.WriteLine(modelId, relation)
        if (debugRecord) {
          debugRecord.createdRelationIds.containmentRelation = relation.expressID
          debugRecord.notes.push(`Created IfcRelContainedInSpatialStructure #${relation.expressID}.`)
        }
      }
    }

    const systemAssignment = writeSanitarySystemAssignment(
      api,
      ifc,
      modelId,
      systemOwnerHistory,
      createdFlowSegmentHandles,
    )
    if (debugMapping) {
      debugMapping.systemAssignment = systemAssignment
    }

    return {
      ifcBytes: api.SaveModel(modelId),
      debugMapping,
    }
  } finally {
    api.CloseModel(modelId)
  }
}

function buildRiserStoreysById(
  api: IfcAPI,
  modelId: number,
  risers: Riser[],
  debugStoreysById: Map<StoreyId, RiserStoreyDebugInfo>,
): Map<StoreyId, StoreySpanInfo> {
  const storeysById = new Map<StoreyId, StoreySpanInfo>()
  for (const riser of risers) {
    if (storeysById.has(riser.storeyId)) continue
    const storeyInfo = resolveStoreyDebugInfo(api, modelId, riser.storeyId, debugStoreysById)
    storeysById.set(riser.storeyId, {
      id: riser.storeyId,
      name: storeyInfo.name,
      elevation: storeyInfo.elevation,
    })
  }
  return storeysById
}

function groupRisersByStackId(
  risers: Riser[],
  storeysById: Map<StoreyId, StoreySpanInfo>,
): StackGroup[] {
  const risersByStack = new Map<string, Riser[]>()
  for (const riser of risers) {
    const group = risersByStack.get(riser.stackId)
    if (group) group.push(riser)
    else risersByStack.set(riser.stackId, [riser])
  }

  const stackGroups: StackGroup[] = []
  for (const [stackId, members] of risersByStack) {
    if (members.length === 0) continue

    const first = members[0]
    const stackLabel = first.stackLabel.trim() || stackId
    const firstStorey = requireStoreySpanInfo(storeysById, first.storeyId, stackLabel, stackId)

    for (const member of members.slice(1)) {
      const memberStorey = requireStoreySpanInfo(storeysById, member.storeyId, stackLabel, stackId)
      const deltaX = Math.abs(member.position.x - first.position.x)
      const deltaZ = Math.abs(member.position.z - first.position.z)
      if (deltaX > RISER_STACK_ALIGNMENT_EPSILON || deltaZ > RISER_STACK_ALIGNMENT_EPSILON) {
        throw new Error(
          `Riser stack ${stackLabel} (${stackId}) has misaligned floors: ` +
          `floor ${formatStoreyName(firstStorey)} at (${first.position.x}, ${first.position.z}) ` +
          `vs floor ${formatStoreyName(memberStorey)} at (${member.position.x}, ${member.position.z})`,
        )
      }
    }

    const orderedMembers = [...members].sort((left, right) =>
      getStoreyElevation(left, storeysById) - getStoreyElevation(right, storeysById),
    )
    const bottomRiser = orderedMembers[0]
    const topRiser = orderedMembers[orderedMembers.length - 1]

    stackGroups.push({
      stackId,
      stackLabel,
      canonicalPosition: { ...bottomRiser.position },
      bottomRiser,
      topRiser,
      members: orderedMembers,
    })
  }

  return stackGroups
}

function requireStoreySpanInfo(
  storeysById: Map<StoreyId, StoreySpanInfo>,
  storeyId: StoreyId,
  stackLabel: string,
  stackId: string,
): StoreySpanInfo {
  const storey = storeysById.get(storeyId)
  if (!storey || !Number.isFinite(storey.elevation)) {
    throw new Error(
      `Riser stack ${stackLabel} (${stackId}) references storey ${storeyId} without a resolvable elevation.`,
    )
  }
  return storey
}

function getStoreyElevation(
  riser: Riser,
  storeysById: Map<StoreyId, StoreySpanInfo>,
): number {
  const storey = storeysById.get(riser.storeyId)
  const elevation = storey?.elevation
  if (typeof elevation !== 'number' || !Number.isFinite(elevation)) {
    throw new Error(`Riser ${riser.id} references storey ${riser.storeyId} without a resolvable elevation.`)
  }
  return elevation
}

function formatStoreyName(storey: StoreySpanInfo): string {
  return storey.name ?? `#${storey.id}`
}

function resolveLengthScaleToMillimetres(api: IfcAPI, modelId: number): number {
  const projectType = api.GetTypeCodeFromName('IFCPROJECT')
  const projectIds = api.GetLineIDsWithType(modelId, projectType)
  if (projectIds.size() === 0) return 1000

  const project = api.GetLine(modelId, projectIds.get(0), false) as {
    UnitsInContext?: IfcHandle | null
  } | null
  const assignmentId = project?.UnitsInContext?.value ?? null
  if (assignmentId === null) return 1000

  const assignment = api.GetLine(modelId, assignmentId, false) as {
    Units?: Array<IfcHandle | null> | null
  } | null

  for (const unitRef of assignment?.Units ?? []) {
    const unitId = unitRef?.value ?? null
    if (unitId === null) continue
    if (api.GetNameFromTypeCode(api.GetLineType(modelId, unitId)) !== 'IfcSIUnit') continue

    const unit = api.GetLine(modelId, unitId, false) as {
      UnitType?: { value?: string } | null
      Name?: { value?: string } | null
      Prefix?: { value?: string } | null
    } | null
    if (unit?.UnitType?.value !== 'LENGTHUNIT') continue
    if (unit?.Name?.value !== 'METRE') continue

    switch (unit?.Prefix?.value ?? null) {
      case 'MILLI':
        return 1
      case 'CENTI':
        return 10
      case null:
      case undefined:
        return 1000
      default:
        throw new Error(`Unsupported length prefix ${unit.Prefix?.value}.`)
    }
  }

  return 1000
}

function resolveBodyContext(api: IfcAPI, modelId: number): number {
  const bodyContextId = 24
  if (api.GetNameFromTypeCode(api.GetLineType(modelId, bodyContextId)) === 'IfcGeometricRepresentationSubContext') {
    return bodyContextId
  }

  const shapeType = api.GetTypeCodeFromName('IFCSHAPEREPRESENTATION')
  const shapeIds = api.GetLineIDsWithType(modelId, shapeType)
  for (let i = 0; i < shapeIds.size(); i += 1) {
    const shape = api.GetLine(modelId, shapeIds.get(i), false) as {
      ContextOfItems?: IfcHandle | null
    } | null
    const contextId = shape?.ContextOfItems?.value ?? null
    if (contextId === null) continue
    const context = api.GetLine(modelId, contextId, false) as {
      ContextIdentifier?: { value?: string } | null
    } | null
    if (context?.ContextIdentifier?.value === 'Body') {
      return contextId
    }
  }

  throw new Error('Could not resolve a Body representation context.')
}

function resolveLocalPlacementWorldMatrix(api: IfcAPI, modelId: number, placementId: number): Matrix4 {
  const placement = api.GetLine(modelId, placementId, false) as {
    PlacementRelTo?: IfcHandle | null
    RelativePlacement?: IfcHandle | null
  } | null
  if (!placement) throw new Error(`Missing IfcLocalPlacement #${placementId}.`)

  const parentMatrix =
    placement.PlacementRelTo?.value != null
      ? resolveLocalPlacementWorldMatrix(api, modelId, placement.PlacementRelTo.value)
      : new Matrix4()

  const relativePlacementId = placement.RelativePlacement?.value ?? null
  if (relativePlacementId === null) return parentMatrix

  return parentMatrix.multiply(resolveAxisPlacementMatrix(api, modelId, relativePlacementId))
}

function resolveAxisPlacementMatrix(api: IfcAPI, modelId: number, placementId: number): Matrix4 {
  const placement = api.GetLine(modelId, placementId, false) as {
    Location?: IfcHandle | null
    Axis?: IfcHandle | null
    RefDirection?: IfcHandle | null
  } | null
  if (!placement) throw new Error(`Missing axis placement #${placementId}.`)

  const location = readCoordinates(api, modelId, placement.Location?.value ?? null, [0, 0, 0])
  const zAxis = readDirection(api, modelId, placement.Axis?.value ?? null, new Vector3(0, 0, 1))
  const xHint = readDirection(api, modelId, placement.RefDirection?.value ?? null, new Vector3(1, 0, 0))
  const yAxis = new Vector3().crossVectors(zAxis, xHint).normalize()
  const xAxis = new Vector3().crossVectors(yAxis, zAxis).normalize()

  const matrix = new Matrix4()
  matrix.makeBasis(xAxis, yAxis, zAxis)
  matrix.setPosition(location)
  return matrix
}

function readCoordinates(
  api: IfcAPI,
  modelId: number,
  pointId: number | null,
  fallback: [number, number, number],
): Vector3 {
  if (pointId === null) return new Vector3(...fallback)
  const point = api.GetLine(modelId, pointId, false) as {
    Coordinates?: Array<{ value?: number } | number> | null
  } | null
  const coords = (point?.Coordinates ?? []).map((value) => Number((value as { value?: number })?.value ?? value))
  return new Vector3(
    Number.isFinite(coords[0]) ? coords[0] : fallback[0],
    Number.isFinite(coords[1]) ? coords[1] : fallback[1],
    Number.isFinite(coords[2]) ? coords[2] : fallback[2],
  )
}

function readDirection(
  api: IfcAPI,
  modelId: number,
  directionId: number | null,
  fallback: Vector3,
): Vector3 {
  if (directionId === null) return fallback.clone()
  const direction = api.GetLine(modelId, directionId, false) as {
    DirectionRatios?: Array<{ value?: number } | number> | null
  } | null
  const ratios = (direction?.DirectionRatios ?? []).map((value) => Number((value as { value?: number })?.value ?? value))
  const vector = new Vector3(
    Number.isFinite(ratios[0]) ? ratios[0] : fallback.x,
    Number.isFinite(ratios[1]) ? ratios[1] : fallback.y,
    Number.isFinite(ratios[2]) ? ratios[2] : fallback.z,
  )
  return vector.lengthSq() > 1e-9 ? vector.normalize() : fallback.clone()
}

function toIfcWorldPlanPoint(
  position: { x: number; y: number; z: number },
  sourceUnitsPerViewerUnit: number,
  storeyWorldZ: number,
): Vector3 {
  return new Vector3(
    position.x * sourceUnitsPerViewerUnit,
    -position.z * sourceUnitsPerViewerUnit,
    storeyWorldZ,
  )
}

function resolveStoreyContext(
  api: IfcAPI,
  modelId: number,
  storeyId: StoreyId,
  relationType: number,
): StoreyContext {
  const targetStorey = api.GetLine(modelId, storeyId, false) as {
    OwnerHistory?: IfcHandle | null
    ObjectPlacement?: IfcHandle | null
  } | null
  if (!targetStorey) {
    throw new Error(`Storey #${storeyId} is missing from the IFC model.`)
  }

  const targetStoreyPlacementId = targetStorey.ObjectPlacement?.value ?? null
  if (targetStoreyPlacementId === null) {
    throw new Error(`Storey #${storeyId} is missing ObjectPlacement.`)
  }

  const containment = findStoreyContainmentRelation(api, modelId, relationType, storeyId)

  return {
    storeyId,
    targetStoreyPlacementId,
    ownerHistory: toHandle(targetStorey.OwnerHistory),
    containment,
  }
}

function resolveRiserPlacement(
  api: IfcAPI,
  modelId: number,
  storeyContext: StoreyContext,
  riser: Riser,
  sourceUnitsPerViewerUnit: number,
): ResolvedRiserPlacement {
  const exportPosition = riser.position

  const storeyWorldMatrix = resolveLocalPlacementWorldMatrix(api, modelId, storeyContext.targetStoreyPlacementId)
  const inverseStoreyWorldMatrix = storeyWorldMatrix.clone().invert()
  const storeyWorldOrigin = new Vector3().setFromMatrixPosition(storeyWorldMatrix)
  const ifcWorldPoint = toIfcWorldPlanPoint(exportPosition, sourceUnitsPerViewerUnit, storeyWorldOrigin.z)
  const localPoint = ifcWorldPoint.clone().applyMatrix4(inverseStoreyWorldMatrix)
  const parentPlacementAxes = readLocalPlacementAxes(api, modelId, storeyContext.targetStoreyPlacementId)

  return {
    webPositionUsedForExport: vectorLikeToDebugPoint(exportPosition),
    worldOrModelPosition: vectorToDebugPoint(ifcWorldPoint),
    finalIfcLocalPlacement: vectorToDebugPoint(localPoint),
    parentPlacementOrigin: vectorToDebugPoint(storeyWorldOrigin),
    parentPlacementAxis: vectorToDebugPoint(parentPlacementAxes.axis),
    parentPlacementRefDirection: vectorToDebugPoint(parentPlacementAxes.refDirection),
  }
}

function createDebugArtifact(
  options: FullIfcRiserDebugOptions,
  schema: string,
  sourceFloorPlanBounds: PlanBounds | null,
): FullIfcRiserDebugArtifact {
  return {
    exportRunId: options.exportRunId ?? createExportRunId(),
    timestamp: options.timestamp ?? new Date().toISOString(),
    sourceIfcName: options.sourceIfcName ?? null,
    schema,
    sourceFloorPlanBounds,
    systemAssignment: null,
    risers: [],
    warnings: [],
    notes: [
      'Generated by the BIMPipe full IFC export flow.',
      'worldOrModelPosition and finalIfcLocalPlacement are in source IFC length units.',
      'Each riser is now exported as one continuous IfcFlowSegment per stack; previous per-storey 3 m segments are no longer produced.',
    ],
  }
}

function buildRiserDebugRecord(
  api: IfcAPI,
  modelId: number,
  artifact: FullIfcRiserDebugArtifact,
  schema: string,
  storeyContext: StoreyContext,
  storeysById: Map<StoreyId, StoreySpanInfo>,
  stack: StackGroup,
  placement: ResolvedRiserPlacement,
  writtenRiser: WrittenRiser,
  extrusionLengthSourceUnits: number,
): FullIfcRiserDebugRecord {
  const bottomStoreyInfo = storeysById.get(stack.bottomRiser.storeyId) ?? {
    id: stack.bottomRiser.storeyId,
    name: null,
    elevation: null,
  }
  const topStoreyInfo = storeysById.get(stack.topRiser.storeyId) ?? {
    id: stack.topRiser.storeyId,
    name: null,
    elevation: null,
  }
  const warnings = [
    ...(!bottomStoreyInfo.name ? ['Storey name was not available from app state or IFC line.'] : []),
  ]

  return {
    exportRunId: artifact.exportRunId,
    timestamp: artifact.timestamp,
    sourceIfcName: artifact.sourceIfcName,
    schema,
    riserId: stack.bottomRiser.id,
    riserTag: stack.stackLabel,
    floorId: stack.bottomRiser.storeyId,
    floorName: bottomStoreyInfo.name,
    storeyEntityId: storeyContext.storeyId,
    storeyName: bottomStoreyInfo.name,
    storeyElevation: bottomStoreyInfo.elevation,
    webPositionRaw: vectorLikeToDebugPoint(stack.canonicalPosition),
    webPositionUsedForExport: placement.webPositionUsedForExport,
    floorLocalPosition: placement.finalIfcLocalPlacement,
    worldOrModelPosition: placement.worldOrModelPosition,
    chosenAnchorEntityId: storeyContext.targetStoreyPlacementId,
    chosenAnchorType: getIfcTypeName(api, modelId, storeyContext.targetStoreyPlacementId),
    chosenParentPlacementId: storeyContext.targetStoreyPlacementId,
    parentPlacementOrigin: placement.parentPlacementOrigin,
    parentPlacementAxis: placement.parentPlacementAxis,
    parentPlacementRefDirection: placement.parentPlacementRefDirection,
    finalIfcLocalPlacement: placement.finalIfcLocalPlacement,
    bottomStoreyEntityId: stack.bottomRiser.storeyId,
    bottomStoreyName: bottomStoreyInfo.name,
    bottomStoreyElevation: bottomStoreyInfo.elevation,
    topStoreyEntityId: stack.topRiser.storeyId,
    topStoreyName: topStoreyInfo.name,
    topStoreyElevation: topStoreyInfo.elevation,
    coveredStoreyIds: stack.members.map((member) => member.storeyId),
    extrusionLengthSourceUnits,
    createdEntityIds: compactIdMap(writtenRiser.createdEntityIds),
    createdRelationIds: compactIdMap(writtenRiser.createdRelationIds),
    warnings,
    notes: [
      'Plan position written verbatim from web frame after axis swap and storey-chain inverse.',
    ],
  }
}

function resolveStoreyDebugInfo(
  api: IfcAPI,
  modelId: number,
  storeyId: StoreyId,
  debugStoreysById: Map<StoreyId, RiserStoreyDebugInfo>,
): { name: string | null; elevation: number | null } {
  const appStorey = debugStoreysById.get(storeyId)
  if (appStorey) {
    return {
      name: appStorey.name,
      elevation: appStorey.elevation,
    }
  }

  const ifcStorey = api.GetLine(modelId, storeyId, false) as {
    Name?: { value?: string } | string | null
    Elevation?: { value?: number } | number | null
  } | null

  return {
    name: readOptionalStringValue(ifcStorey?.Name),
    elevation: readOptionalNumberValue(ifcStorey?.Elevation),
  }
}

function readLocalPlacementAxes(
  api: IfcAPI,
  modelId: number,
  placementId: number,
): { axis: Vector3; refDirection: Vector3 } {
  const placement = api.GetLine(modelId, placementId, false) as {
    RelativePlacement?: IfcHandle | null
  } | null
  const relativePlacementId = placement?.RelativePlacement?.value ?? null
  if (relativePlacementId === null) {
    return {
      axis: new Vector3(0, 0, 1),
      refDirection: new Vector3(1, 0, 0),
    }
  }

  const relativePlacement = api.GetLine(modelId, relativePlacementId, false) as {
    Axis?: IfcHandle | null
    RefDirection?: IfcHandle | null
  } | null

  return {
    axis: readDirection(api, modelId, relativePlacement?.Axis?.value ?? null, new Vector3(0, 0, 1)),
    refDirection: readDirection(api, modelId, relativePlacement?.RefDirection?.value ?? null, new Vector3(1, 0, 0)),
  }
}

function compactIdMap(ids: Record<string, number | undefined>): Record<string, number> {
  return Object.fromEntries(
    Object.entries(ids).filter((entry): entry is [string, number] => typeof entry[1] === 'number'),
  )
}

function vectorToDebugPoint(vector: Vector3): Point3Debug {
  return {
    x: vector.x,
    y: vector.y,
    z: vector.z,
  }
}

function vectorLikeToDebugPoint(point: { x: number; y: number; z: number }): Point3Debug {
  return {
    x: point.x,
    y: point.y,
    z: point.z,
  }
}

function readOptionalStringValue(value: { value?: string } | string | null | undefined): string | null {
  if (typeof value === 'string') return value
  if (typeof value === 'object' && typeof value?.value === 'string') return value.value
  return null
}

function readOptionalNumberValue(value: { value?: number } | number | null | undefined): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value
  if (typeof value === 'object' && typeof value?.value === 'number' && Number.isFinite(value.value)) {
    return value.value
  }
  return null
}

function getIfcTypeName(api: IfcAPI, modelId: number, expressId: number): string {
  const typeCode = api.GetLineType(modelId, expressId)
  if (typeCode < 0) return 'Unknown'
  return api.GetNameFromTypeCode(typeCode)
}

function createExportRunId(): string {
  return globalThis.crypto?.randomUUID?.() ?? `riser-export-${Date.now().toString(36)}`
}

function writeMinimalRiser(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  schema: string,
  bodyContextId: number,
  targetStoreyPlacementId: number,
  ownerHistory: IfcHandle | null,
  riser: Riser,
  localPoint: Vector3,
  riserRadiusSourceUnits: number,
  riserExtrusionLengthSourceUnits: number,
  millimetresPerSourceUnit: number,
): WrittenRiser {
  const {
    IFCAXIS2PLACEMENT2D,
    IFCAXIS2PLACEMENT3D,
    IFCCARTESIANPOINT,
    IFCCIRCLEPROFILEDEF,
    IFCEXTRUDEDAREASOLID,
    IFCFLOWSEGMENT,
    IFCIDENTIFIER,
    IFCLABEL,
    IFCLENGTHMEASURE,
    IFCLOCALPLACEMENT,
    IFCMATERIAL,
    IFCPIPESEGMENT,
    IFCPIPESEGMENTTYPE,
    IFCPRODUCTDEFINITIONSHAPE,
    IFCRELASSOCIATESMATERIAL,
    IFCRELDEFINESBYTYPE,
    IFCSHAPEREPRESENTATION,
  } = ifc

  const point2d = writeLabeledLine(api, modelId, 'profile point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
    ],
  })

  const dir2d = writeLabeledLine(api, modelId, 'profile direction', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCDIRECTION'),
    DirectionRatios: [1, 0],
  })

  const profilePlacement = writeLabeledLine(api, modelId, 'profile placement', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT2D,
    Location: handleRef(point2d.expressID),
    RefDirection: handleRef(dir2d.expressID),
  })

  const profile = writeLabeledLine(api, modelId, 'circle profile', {
    expressID: -1,
    type: IFCCIRCLEPROFILEDEF,
    ProfileType: { type: 3, value: 'AREA' },
    ProfileName: null,
    Position: handleRef(profilePlacement.expressID),
    Radius: api.CreateIfcType(modelId, IFCLENGTHMEASURE, riserRadiusSourceUnits),
  })

  const point3d = writeLabeledLine(api, modelId, 'swept solid point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
    ],
  })

  const dirZ = writeLabeledLine(api, modelId, 'vertical direction', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCDIRECTION'),
    DirectionRatios: [0, 0, 1],
  })

  const dirX = writeLabeledLine(api, modelId, 'x direction', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCDIRECTION'),
    DirectionRatios: [1, 0, 0],
  })

  const sweptPlacement = writeLabeledLine(api, modelId, 'swept solid placement', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT3D,
    Location: handleRef(point3d.expressID),
    Axis: handleRef(dirZ.expressID),
    RefDirection: handleRef(dirX.expressID),
  })

  const solid = writeLabeledLine(api, modelId, 'extruded solid', {
    expressID: -1,
    type: IFCEXTRUDEDAREASOLID,
    SweptArea: handleRef(profile.expressID),
    Position: handleRef(sweptPlacement.expressID),
    ExtrudedDirection: handleRef(dirZ.expressID),
    Depth: api.CreateIfcType(modelId, IFCLENGTHMEASURE, riserExtrusionLengthSourceUnits),
  })

  const shape = writeLabeledLine(api, modelId, 'shape representation', {
    expressID: -1,
    type: IFCSHAPEREPRESENTATION,
    ContextOfItems: handleRef(bodyContextId),
    RepresentationIdentifier: api.CreateIfcType(modelId, IFCLABEL, 'Body'),
    RepresentationType: api.CreateIfcType(modelId, IFCLABEL, 'SweptSolid'),
    Items: [handleRef(solid.expressID)],
  })

  const productShape = writeLabeledLine(api, modelId, 'product definition shape', {
    expressID: -1,
    type: IFCPRODUCTDEFINITIONSHAPE,
    Name: null,
    Description: null,
    Representations: [handleRef(shape.expressID)],
  })

  const placementPoint = writeLabeledLine(api, modelId, 'object placement point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, localPoint.x),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, localPoint.y),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, localPoint.z),
    ],
  })

  const placementAxis = writeLabeledLine(api, modelId, 'object placement axis', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT3D,
    Location: handleRef(placementPoint.expressID),
    Axis: handleRef(dirZ.expressID),
    RefDirection: handleRef(dirX.expressID),
  })

  const targetStoreyPlacement = api.GetLine(modelId, targetStoreyPlacementId, false)
  const localPlacement = createLabeledEntity(
    api,
    modelId,
    'local placement',
    IFCLOCALPLACEMENT,
    targetStoreyPlacement,
    placementAxis,
  )
  api.WriteLine(modelId, localPlacement)

  const stackLabel = riser.stackLabel.trim() || 'R1'
  const riserName = `BIMPipe ${stackLabel}`
  const riserElementType = schema === 'IFC2X3' ? IFCFLOWSEGMENT : IFCPIPESEGMENT

  const riserElement = writeLabeledLine(api, modelId, 'riser element', {
    expressID: -1,
    type: riserElementType,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, IFCLABEL, riserName),
    Description: null,
    ObjectType: api.CreateIfcType(modelId, IFCLABEL, 'BIMPipeRiser'),
    ObjectPlacement: handleRef(localPlacement.expressID),
    Representation: handleRef(productShape.expressID),
    Tag: api.CreateIfcType(modelId, IFCIDENTIFIER, stackLabel),
    ...(schema === 'IFC2X3' ? {} : { PredefinedType: { type: 3, value: 'NOTDEFINED' } }),
  })

  let pipeSegmentType: IfcWritableLine | null = null
  let typeRelation: IfcEntityRef | null = null
  let typeCommonPset: { pset: IfcEntityRef; relation: IfcEntityRef } | null = null
  if (schema === 'IFC2X3') {
    pipeSegmentType = writeLabeledLine(api, modelId, 'pipe segment type', {
      expressID: -1,
      type: IFCPIPESEGMENTTYPE,
      GlobalId: api.CreateIFCGloballyUniqueId(modelId),
      OwnerHistory: ownerHistory,
      Name: api.CreateIfcType(modelId, IFCLABEL, RISER_PIPE_TYPE_NAME),
      Description: null,
      ApplicableOccurrence: null,
      HasPropertySets: [],
      RepresentationMaps: null,
      Tag: api.CreateIfcType(modelId, IFCLABEL, `${stackLabel}-Type`),
      ElementType: api.CreateIfcType(modelId, IFCLABEL, 'PVC 110 Pipe Type'),
      PredefinedType: { type: 3, value: 'RIGIDSEGMENT' },
    })

    typeRelation = writeLabeledLine(api, modelId, 'type relation', {
      expressID: -1,
      type: IFCRELDEFINESBYTYPE,
      GlobalId: api.CreateIFCGloballyUniqueId(modelId),
      OwnerHistory: ownerHistory,
      Name: null,
      Description: null,
      RelatedObjects: [handleRef(riserElement.expressID)],
      RelatingType: handleRef(pipeSegmentType.expressID),
    })

    typeCommonPset = writePipeSegmentTypeCommonPset(
      api,
      ifc,
      modelId,
      ownerHistory,
      pipeSegmentType,
      stackLabel,
      millimetresPerSourceUnit,
    )
    pipeSegmentType.HasPropertySets = [handleRef(typeCommonPset.pset.expressID)]
    writeLabeledLine(api, modelId, 'pipe segment type inline property sets', pipeSegmentType)
  }

  const material = writeLabeledLine(api, modelId, 'material', {
    expressID: -1,
    type: IFCMATERIAL,
    Name: api.CreateIfcType(modelId, IFCLABEL, RISER_MATERIAL_NAME),
  })

  const materialRelation = writeLabeledLine(api, modelId, 'material relation', {
    expressID: -1,
    type: IFCRELASSOCIATESMATERIAL,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: null,
    Description: null,
    RelatedObjects: [handleRef(riserElement.expressID)],
    RelatingMaterial: material,
  })

  const occurrencePset = writeFlowSegmentOccurrencePset(
    api,
    ifc,
    modelId,
    ownerHistory,
    riserElement,
    riserExtrusionLengthSourceUnits,
  )
  const baseQuantities = writePipeSegmentBaseQuantities(
    api,
    ifc,
    modelId,
    ownerHistory,
    riserElement,
    riserExtrusionLengthSourceUnits,
  )

  return {
    element: riserElement,
    createdEntityIds: {
      riserElement: riserElement.expressID,
      flowSegment: schema === 'IFC2X3' ? riserElement.expressID : undefined,
      pipeSegment: schema === 'IFC2X3' ? undefined : riserElement.expressID,
      pipeSegmentType: pipeSegmentType?.expressID,
      psetTypeCommon: typeCommonPset?.pset.expressID,
      psetOccurrence: occurrencePset.pset.expressID,
      qtoSet: baseQuantities.qtoSet.expressID,
      material: material.expressID,
      circleProfile: profile.expressID,
      extrudedAreaSolid: solid.expressID,
      shapeRepresentation: shape.expressID,
      productDefinitionShape: productShape.expressID,
      localPlacement: localPlacement.expressID,
      placementAxis: placementAxis.expressID,
      placementPoint: placementPoint.expressID,
      profilePoint: point2d.expressID,
      profileDirection: dir2d.expressID,
      profilePlacement: profilePlacement.expressID,
      sweptSolidPoint: point3d.expressID,
      verticalDirection: dirZ.expressID,
      xDirection: dirX.expressID,
      sweptSolidPlacement: sweptPlacement.expressID,
    },
    createdRelationIds: {
      typeRelation: typeRelation?.expressID,
      psetTypeCommonRel: typeCommonPset?.relation.expressID,
      psetOccurrenceRel: occurrencePset.relation.expressID,
      qtoSetRel: baseQuantities.relation.expressID,
      materialRelation: materialRelation.expressID,
    },
  }
}

function writePipeSegmentTypeCommonPset(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  typeHandle: IfcEntityRef,
  stackLabel: string,
  millimetresPerSourceUnit: number,
): { pset: IfcEntityRef; relation: IfcEntityRef } {
  const nominalDiameter = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'NominalDiameter',
    api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
    RISER_OUTER_DIAMETER_MM / millimetresPerSourceUnit,
  )
  const outerDiameter = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'OuterDiameter',
    api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
    RISER_OUTER_DIAMETER_MM / millimetresPerSourceUnit,
  )
  const innerDiameter = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'InnerDiameter',
    api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
    RISER_INNER_DIAMETER_MM / millimetresPerSourceUnit,
  )
  const wallThickness = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'WallThickness',
    api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
    RISER_WALL_THICKNESS_MM / millimetresPerSourceUnit,
  )
  const roughness = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'Roughness',
    api.GetTypeCodeFromName('IFCLENGTHMEASURE'),
    RISER_ROUGHNESS_MM / millimetresPerSourceUnit,
  )
  const reference = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'Reference',
    api.GetTypeCodeFromName('IFCIDENTIFIER'),
    stackLabel,
  )
  const pset = writePropertySet(api, ifc, modelId, ownerHistory, 'Pset_PipeSegmentTypeCommon', [
    nominalDiameter,
    outerDiameter,
    innerDiameter,
    wallThickness,
    roughness,
    reference,
  ])
  const relation = writeRelDefinesByProperties(api, modelId, ownerHistory, [typeHandle], pset)

  return { pset, relation }
}

function writePipeSegmentBaseQuantities(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  riserHandle: IfcEntityRef,
  extrusionLengthSourceUnits: number,
): { qtoSet: IfcEntityRef; relation: IfcEntityRef } {
  const netLength = writeQuantityLength(api, ifc, modelId, 'NetLength', extrusionLengthSourceUnits)
  const grossLength = writeQuantityLength(api, ifc, modelId, 'GrossLength', extrusionLengthSourceUnits)
  const qtoSet = writeLabeledLine(api, modelId, 'pipe segment base quantities', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCELEMENTQUANTITY'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'Qto_PipeSegmentBaseQuantities'),
    Description: null,
    MethodOfMeasurement: null,
    Quantities: [handleRef(netLength.expressID), handleRef(grossLength.expressID)],
  })
  const relation = writeRelDefinesByProperties(api, modelId, ownerHistory, [riserHandle], qtoSet)

  return { qtoSet, relation }
}

function writeQuantityLength(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  name: string,
  lengthValue: number,
): IfcEntityRef {
  return writeLabeledLine(api, modelId, `quantity ${name}`, {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCQUANTITYLENGTH'),
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, name),
    Description: null,
    Unit: null,
    LengthValue: api.CreateIfcType(modelId, ifc.IFCLENGTHMEASURE, lengthValue),
  })
}

function writeFlowSegmentOccurrencePset(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  riserHandle: IfcEntityRef,
  extrusionLengthSourceUnits: number,
): { pset: IfcEntityRef; relation: IfcEntityRef } {
  const systemType = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'SystemType',
    api.GetTypeCodeFromName('IFCLABEL'),
    'SANITARY',
  )
  const flowDirection = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'FlowDirection',
    api.GetTypeCodeFromName('IFCLABEL'),
    'NOTDEFINED',
  )
  const length = writePropertySingleValue(
    api,
    ifc,
    modelId,
    'Length',
    api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
    extrusionLengthSourceUnits,
  )
  const pset = writePropertySet(api, ifc, modelId, ownerHistory, 'Pset_FlowSegmentOccurrence', [
    systemType,
    flowDirection,
    length,
  ])
  const relation = writeRelDefinesByProperties(api, modelId, ownerHistory, [riserHandle], pset)

  return { pset, relation }
}

function writePropertySingleValue(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  propertyName: string,
  valueType: number,
  value: string | number,
): IfcEntityRef {
  return writeLabeledLine(api, modelId, `property ${propertyName}`, {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCPROPERTYSINGLEVALUE'),
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, propertyName),
    Description: null,
    NominalValue: api.CreateIfcType(modelId, valueType, value),
    Unit: null,
  })
}

function writePropertySet(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  name: string,
  properties: IfcEntityRef[],
): IfcEntityRef {
  return writeLabeledLine(api, modelId, `property set ${name}`, {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCPROPERTYSET'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, name),
    Description: null,
    HasProperties: properties.map((property) => handleRef(property.expressID)),
  })
}

function writeRelDefinesByProperties(
  api: IfcAPI,
  modelId: number,
  ownerHistory: IfcHandle | null,
  relatedObjects: IfcEntityRef[],
  propertySet: IfcEntityRef,
): IfcEntityRef {
  return writeLabeledLine(api, modelId, 'property relation', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELDEFINESBYPROPERTIES'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: null,
    Description: null,
    RelatedObjects: relatedObjects.map((object) => handleRef(object.expressID)),
    RelatingPropertyDefinition: handleRef(propertySet.expressID),
  })
}

function writeSanitarySystemAssignment(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  riserHandles: IfcHandle[],
): FullIfcSystemAssignmentDebug {
  const buildingType = api.GetTypeCodeFromName('IFCBUILDING')
  const buildingIds = api.GetLineIDsWithType(modelId, buildingType)
  if (buildingIds.size() === 0) {
    throw new Error('Source IFC has no IfcBuilding; cannot attach BIMPipe sanitary system.')
  }

  const buildingId = buildingIds.get(0)
  const system = writeLabeledLine(api, modelId, 'sanitary system', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCSYSTEM'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, RISER_SYSTEM_NAME),
    Description: api.CreateIfcType(modelId, api.GetTypeCodeFromName('IFCTEXT'), RISER_SYSTEM_DESCRIPTION),
    ObjectType: api.CreateIfcType(modelId, ifc.IFCLABEL, 'SANITARY'),
  })

  const groupRelation = writeLabeledLine(api, modelId, 'sanitary system assignment', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELASSIGNSTOGROUP'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe Sanitary System Assignment'),
    Description: null,
    RelatedObjects: riserHandles,
    RelatedObjectsType: api.CreateIfcType(modelId, ifc.IFCLABEL, 'IFCFLOWSEGMENT'),
    RelatingGroup: handleRef(system.expressID),
  })

  const serviceRelation = writeLabeledLine(api, modelId, 'sanitary system service', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELSERVICESBUILDINGS'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe Sanitary System Service'),
    Description: null,
    RelatedBuildings: [handleRef(buildingId)],
    RelatingSystem: handleRef(system.expressID),
  })

  return {
    ifcSystemId: system.expressID,
    ifcRelAssignsToGroupId: groupRelation.expressID,
    ifcRelServicesBuildingsId: serviceRelation.expressID,
    ifcBuildingId: buildingId,
    name: RISER_SYSTEM_NAME,
    objectType: 'SANITARY',
    description: RISER_SYSTEM_DESCRIPTION,
  }
}

function findStoreyContainmentRelation(
  api: IfcAPI,
  modelId: number,
  relationType: number,
  storeyId: StoreyId,
): {
  expressID: number
  type: number
  RelatedElements?: unknown[]
  RelatingStructure?: IfcHandle | null
} | null {
  const relationIds = api.GetLineIDsWithType(modelId, relationType)

  for (let i = 0; i < relationIds.size(); i++) {
    const relation = api.GetLine(modelId, relationIds.get(i), false) as {
      expressID: number
      type: number
      RelatedElements?: unknown[]
      RelatingStructure?: IfcHandle | null
    } | null

    const relatingId = relation?.RelatingStructure?.value ?? null
    if (relation && relatingId === storeyId) {
      return relation
    }
  }

  return null
}

function toHandle(value: IfcHandle | { expressID: number } | null | undefined): IfcHandle | null {
  if (!value) return null
  if ('type' in value && value.type === 5 && typeof value.value === 'number') {
    return handleRef(value.value)
  }
  if ('expressID' in value && typeof value.expressID === 'number') return handleRef(value.expressID)
  return null
}

function handleRef(expressId: number): IfcHandle {
  return { type: 5, value: expressId }
}

function writeLabeledLine(api: IfcAPI, modelId: number, label: string, line: IfcWritableLine) {
  try {
    api.WriteLine(modelId, line)
    return line
  } catch (error) {
    throw new Error(`Failed to write ${label}: ${error instanceof Error ? error.message : String(error)}`)
  }
}

function createLabeledEntity(api: IfcAPI, modelId: number, label: string, type: number, ...args: unknown[]) {
  try {
    return api.CreateIfcEntity(modelId, type, ...args) as { expressID: number; type: number }
  } catch (error) {
    throw new Error(`Failed to create ${label}: ${error instanceof Error ? error.message : String(error)}`)
  }
}
