import { Matrix4, Vector3 } from 'three'
import { Handle, type IfcAPI } from 'web-ifc'
import { resolveLocalPlacementWorldMatrix } from './localPlacementMatrix'
import type { Riser, Storey, StoreyId } from '@/domain/types'
import {
  MIN_SANITARY_SEGMENT_PLAN_LENGTH,
  type SanitaryFixtureRoute,
  type SanitaryPipeDiameterMm,
} from '@/shared/routes/buildSanitaryRoutes'
import { planDistance } from '@/shared/routes/planGeometry'
import {
  collectSanitaryExportSegments,
  diameterLabel,
  segmentEndpointElevationsSourceUnits,
  type SanitaryExportSegment,
  type SanitaryExportSkippedSegment,
} from '@/shared/routes/sanitaryRouteExportPlan'

type IfcHandle = { type: 5; value: number }
type IfcWritableLine = { expressID: number; type: number; [key: string]: unknown }
type IfcEntityRef = { expressID: number; type: number }
type ImportedIfcTypes = Awaited<typeof import('web-ifc')>

type StoreyContext = {
  storeyId: StoreyId
  targetStoreyPlacementId: number
  ownerHistory: IfcHandle | null
  containment: {
    expressID: number
    type: number
    RelatedElements?: unknown[]
    RelatingStructure?: IfcHandle | null
  } | null
}

export type WrittenSanitaryRoute = {
  element: IfcEntityRef
  exportSegment: SanitaryExportSegment
}

export type SanitaryRouteExportDebugSummary = {
  receivedRoutes: number
  collectedSegments: number
  writtenElements: number
  skippedSegments: SanitaryExportSkippedSegment[]
}

const SANITARY_ROUTE_SYSTEM_NAME = 'BIMPipe Sanitary Routes'
const SANITARY_ROUTE_SYSTEM_DESCRIPTION = 'Sanitary fixture routes generated by BIMPipe.'

export function writeSanitaryRouteElements(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  schema: string,
  bodyContextId: number,
  routes: SanitaryFixtureRoute[],
  storeys: Pick<Storey, 'id' | 'elevation'>[],
  risers: Riser[],
  sourceUnitsPerViewerUnit: number,
  millimetresPerSourceUnit: number,
  resolveStoreyContext: (storeyId: StoreyId) => StoreyContext,
  resolveViewerPointToStoreyLocal: (
    storeyContext: StoreyContext,
    position: { x: number; y: number; z: number },
    elevationSourceUnits: number,
  ) => Vector3,
  relationContainedInSpatialStructure: number,
  exportNotes?: string[],
): { elements: WrittenSanitaryRoute[]; flowSegmentHandles: IfcHandle[]; debugSummary: SanitaryRouteExportDebugSummary } {
  const skippedSegments: SanitaryExportSkippedSegment[] = []
  const exportSegments = collectSanitaryExportSegments(routes, storeys, risers, skippedSegments)
  if (exportNotes) {
    exportNotes.push(
      `Received ${routes.length} sanitary route(s) for export; collected ${exportSegments.length} export segment(s).`,
    )
  }
  if (exportSegments.length === 0) {
    for (const skipped of skippedSegments) exportNotes?.push(`Skipped sanitary route segment ${skipped.key}: ${skipped.reason}`)
    return {
      elements: [],
      flowSegmentHandles: [],
      debugSummary: {
        receivedRoutes: routes.length,
        collectedSegments: exportSegments.length,
        writtenElements: 0,
        skippedSegments,
      },
    }
  }

  const storeyElevationById = new Map(storeys.map((storey) => [storey.id, storey.elevation]))
  const elements: WrittenSanitaryRoute[] = []
  const flowSegmentHandles: IfcHandle[] = []
  const allRouteElements: IfcEntityRef[] = []
  const typeGroups = new Map<string, RouteTypeGroup>()
  let sharedOwnerHistory: IfcHandle | null = null

  for (const exportSegment of exportSegments) {
    const storeyElevation = storeyElevationById.get(exportSegment.storeyId)
    if (typeof storeyElevation !== 'number' || !Number.isFinite(storeyElevation)) {
      const reason = `Storey #${exportSegment.storeyId} has no elevation.`
      skippedSegments.push({
        key: exportSegment.key,
        fixtureExpressId: exportSegment.fixtureExpressIds[0] ?? -1,
        riserId: exportSegment.riserId,
        reason,
      })
      exportNotes?.push(
        `Skipped sanitary route segment ${exportSegment.key} because ${reason}`,
      )
      continue
    }

    // Guard 1 (plan space): a segment whose endpoints coincide in plan (e.g. after route
    // translation/deduplication) cannot become a valid pipe. Skip it with a note.
    if (planDistance(exportSegment.segment.from, exportSegment.segment.to) < MIN_SANITARY_SEGMENT_PLAN_LENGTH) {
      const reason = 'Its endpoints coincide in plan.'
      skippedSegments.push({
        key: exportSegment.key,
        fixtureExpressId: exportSegment.fixtureExpressIds[0] ?? -1,
        riserId: exportSegment.riserId,
        reason,
      })
      exportNotes?.push(
        `Skipped sanitary route segment ${exportSegment.key} because ${reason}`,
      )
      continue
    }

    const storeyContext = resolveStoreyContext(exportSegment.storeyId)
    const { startElevation, endElevation } = segmentEndpointElevationsSourceUnits(
      exportSegment,
      storeyElevation,
      sourceUnitsPerViewerUnit,
      millimetresPerSourceUnit,
    )

    const startLocal = resolveViewerPointToStoreyLocal(
      storeyContext,
      exportSegment.segment.from,
      startElevation,
    )
    const endLocal = resolveViewerPointToStoreyLocal(
      storeyContext,
      exportSegment.segment.to,
      endElevation,
    )

    // Guard 2 (post-transform): after converting to storey-local IFC coordinates the segment
    // could still collapse to ~zero length. Skip rather than abort the whole export.
    if (startLocal.distanceTo(endLocal) <= MIN_SANITARY_SEGMENT_PLAN_LENGTH) {
      const reason = 'It resolved to zero length in IFC coordinates.'
      skippedSegments.push({
        key: exportSegment.key,
        fixtureExpressId: exportSegment.fixtureExpressIds[0] ?? -1,
        riserId: exportSegment.riserId,
        reason,
      })
      exportNotes?.push(
        `Skipped sanitary route segment ${exportSegment.key} because ${reason}`,
      )
      continue
    }

    const written = writeSlopedPipeSegment(
      api,
      ifc,
      modelId,
      schema,
      bodyContextId,
      storeyContext,
      exportSegment,
      startLocal,
      endLocal,
      millimetresPerSourceUnit,
    )

    elements.push({ element: written.element, exportSegment })
    flowSegmentHandles.push(handleRef(written.element.expressID))
    allRouteElements.push(written.element)
    if (!sharedOwnerHistory) sharedOwnerHistory = storeyContext.ownerHistory

    const groupKey = routeTypeGroupKey(exportSegment)
    const existingGroup = typeGroups.get(groupKey)
    if (existingGroup) {
      existingGroup.elements.push(written.element)
    } else {
      typeGroups.set(groupKey, {
        diameter: exportSegment.segment.pipeDiameterMm,
        kind: exportSegment.segment.kind,
        stackLabel: exportSegment.riserStackLabel,
        exportSegment,
        ownerHistory: storeyContext.ownerHistory,
        elements: [written.element],
      })
    }

    appendToStoreyContainment(
      api,
      ifc,
      modelId,
      storeyContext,
      written.element.expressID,
      relationContainedInSpatialStructure,
    )
  }

  writeSharedRouteMaterial(api, ifc, modelId, sharedOwnerHistory, allRouteElements)

  if (schema === 'IFC2X3') {
    for (const group of typeGroups.values()) {
      writeSharedRoutePipeSegmentType(api, ifc, modelId, group, millimetresPerSourceUnit)
    }
  } else {
    // TODO(BIM-51): IFC4 export does not yet write an IfcPipeSegmentType / Pset_PipeSegmentTypeCommon
    // (NominalDiameter at the type level). ADAM_10 is IFC2X3 so the demo is unaffected, but IFC4
    // route elements currently carry only the occurrence pset.
    exportNotes?.push(
      'IFC4 sanitary route export omits IfcPipeSegmentType/NominalDiameter type psets (not yet implemented).',
    )
  }

  return {
    elements,
    flowSegmentHandles,
    debugSummary: {
      receivedRoutes: routes.length,
      collectedSegments: exportSegments.length,
      writtenElements: elements.length,
      skippedSegments,
    },
  }
}

export function writeSanitaryRouteSystemAssignment(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  schema: string,
  ownerHistory: IfcHandle | null,
  routeHandles: IfcHandle[],
): void {
  if (routeHandles.length === 0) return

  const buildingType = api.GetTypeCodeFromName('IFCBUILDING')
  const buildingIds = api.GetLineIDsWithType(modelId, buildingType)
  if (buildingIds.size() === 0) {
    throw new Error('Source IFC has no IfcBuilding; cannot attach BIMPipe sanitary route system.')
  }

  const buildingId = buildingIds.get(0)
  const system = writeLabeledLine(api, modelId, 'sanitary route system', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCSYSTEM'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, SANITARY_ROUTE_SYSTEM_NAME),
    Description: api.CreateIfcType(
      modelId,
      api.GetTypeCodeFromName('IFCTEXT'),
      SANITARY_ROUTE_SYSTEM_DESCRIPTION,
    ),
    ObjectType: api.CreateIfcType(modelId, ifc.IFCLABEL, 'SANITARY'),
  })

  writeLabeledLine(api, modelId, 'sanitary route system assignment', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELASSIGNSTOGROUP'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe Sanitary Route Assignment'),
    Description: null,
    RelatedObjects: routeHandles,
    ...(schema === 'IFC2X3'
      ? { RelatedObjectsType: api.CreateIfcType(modelId, ifc.IFCLABEL, 'IFCFLOWSEGMENT') }
      : {}),
    RelatingGroup: handleRef(system.expressID),
  })

  if (schema === 'IFC2X3') {
    writeLabeledLine(api, modelId, 'sanitary route system service', {
      expressID: -1,
      type: api.GetTypeCodeFromName('IFCRELSERVICESBUILDINGS'),
      GlobalId: api.CreateIFCGloballyUniqueId(modelId),
      OwnerHistory: ownerHistory,
      Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe Sanitary Route Service'),
      Description: null,
      RelatedBuildings: [handleRef(buildingId)],
      RelatingSystem: handleRef(system.expressID),
    })
  }
}

// Writes only the per-segment geometry, element, and occurrence pset. The shared PVC
// material and pipe-segment type are written once per group by the caller.
function writeSlopedPipeSegment(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  schema: string,
  bodyContextId: number,
  storeyContext: StoreyContext,
  exportSegment: SanitaryExportSegment,
  startLocal: Vector3,
  endLocal: Vector3,
  millimetresPerSourceUnit: number,
): { element: IfcEntityRef } {
  const {
    IFCAXIS2PLACEMENT2D,
    IFCAXIS2PLACEMENT3D,
    IFCCARTESIANPOINT,
    IFCCIRCLEPROFILEDEF,
    IFCEXTRUDEDAREASOLID,
    IFCFLOWSEGMENT,
    IFCIDENTIFIER,
    IFCLABEL,
    IFCLENGTHMEASURE,
    IFCLOCALPLACEMENT,
    IFCPIPESEGMENT,
    IFCPRODUCTDEFINITIONSHAPE,
    IFCSHAPEREPRESENTATION,
  } = ifc

  const pipeVector = endLocal.clone().sub(startLocal)
  const pipeLength = pipeVector.length()
  if (!Number.isFinite(pipeLength) || pipeLength <= 1e-6) {
    throw new Error(`Sanitary route segment ${exportSegment.key} resolved zero length.`)
  }

  const pipeAxis = pipeVector.clone().normalize()
  const radiusSourceUnits =
    (exportSegment.segment.pipeDiameterMm / 2) / millimetresPerSourceUnit

  const point2d = writeLabeledLine(api, modelId, 'route profile point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
    ],
  })

  const dir2d = writeLabeledLine(api, modelId, 'route profile direction', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCDIRECTION'),
    DirectionRatios: [1, 0],
  })

  const profilePlacement = writeLabeledLine(api, modelId, 'route profile placement', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT2D,
    Location: handleRef(point2d.expressID),
    RefDirection: handleRef(dir2d.expressID),
  })

  const profile = writeLabeledLine(api, modelId, 'route circle profile', {
    expressID: -1,
    type: IFCCIRCLEPROFILEDEF,
    ProfileType: { type: 3, value: 'AREA' },
    ProfileName: null,
    Position: handleRef(profilePlacement.expressID),
    Radius: api.CreateIfcType(modelId, IFCLENGTHMEASURE, radiusSourceUnits),
  })

  const point3d = writeLabeledLine(api, modelId, 'route swept solid point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
    ],
  })

  const extrusionDirection = writeDirection(api, modelId, pipeAxis)
  const refDirection = pickPerpendicularReference(pipeAxis)
  const profileZAxis = writeDirection(api, modelId, refDirection)
  const localExtrudeDirection = writeDirection(api, modelId, new Vector3(0, 0, 1))

  const sweptPlacement = writeLabeledLine(api, modelId, 'route swept solid placement', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT3D,
    Location: handleRef(point3d.expressID),
    Axis: handleRef(extrusionDirection.expressID),
    RefDirection: handleRef(profileZAxis.expressID),
  })

  const solid = writeLabeledLine(api, modelId, 'route extruded solid', {
    expressID: -1,
    type: IFCEXTRUDEDAREASOLID,
    SweptArea: handleRef(profile.expressID),
    Position: handleRef(sweptPlacement.expressID),
    ExtrudedDirection: handleRef(localExtrudeDirection.expressID),
    Depth: api.CreateIfcType(modelId, IFCLENGTHMEASURE, pipeLength),
  })

  const shape = writeLabeledLine(api, modelId, 'route shape representation', {
    expressID: -1,
    type: IFCSHAPEREPRESENTATION,
    ContextOfItems: handleRef(bodyContextId),
    RepresentationIdentifier: api.CreateIfcType(modelId, IFCLABEL, 'Body'),
    RepresentationType: api.CreateIfcType(modelId, IFCLABEL, 'SweptSolid'),
    Items: [handleRef(solid.expressID)],
  })

  const productShape = writeLabeledLine(api, modelId, 'route product definition shape', {
    expressID: -1,
    type: IFCPRODUCTDEFINITIONSHAPE,
    Name: null,
    Description: null,
    Representations: [handleRef(shape.expressID)],
  })

  const placementPoint = writeLabeledLine(api, modelId, 'route object placement point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, startLocal.x),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, startLocal.y),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, startLocal.z),
    ],
  })

  const placementAxis = writeLabeledLine(api, modelId, 'route object placement axis', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT3D,
    Location: handleRef(placementPoint.expressID),
    Axis: handleRef(extrusionDirection.expressID),
    RefDirection: handleRef(profileZAxis.expressID),
  })

  const localPlacement = writeLabeledLine(api, modelId, 'route local placement', {
    expressID: -1,
    type: IFCLOCALPLACEMENT,
    PlacementRelTo: handleRef(storeyContext.targetStoreyPlacementId),
    RelativePlacement: handleRef(placementAxis.expressID),
  })

  const diameter = exportSegment.segment.pipeDiameterMm
  const routeElementType = schema === 'IFC2X3' ? IFCFLOWSEGMENT : IFCPIPESEGMENT
  const tag = `${exportSegment.riserStackLabel}-${diameter}-${exportSegment.segment.kind}`

  const routeElement = writeLabeledLine(api, modelId, 'sanitary route element', {
    expressID: -1,
    type: routeElementType,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: storeyContext.ownerHistory,
    Name: api.CreateIfcType(modelId, IFCLABEL, exportSegment.label),
    Description: api.CreateIfcType(
      modelId,
      IFCLABEL,
      `Sanitary ${exportSegment.segment.kind} route; ${(exportSegment.slope * 100).toFixed(1)}% slope toward riser.`,
    ),
    ObjectType: api.CreateIfcType(modelId, IFCLABEL, 'BIMPipeSanitaryRoute'),
    ObjectPlacement: handleRef(localPlacement.expressID),
    Representation: handleRef(productShape.expressID),
    Tag: api.CreateIfcType(modelId, IFCIDENTIFIER, tag),
    ...(schema === 'IFC2X3' ? {} : { PredefinedType: { type: 3, value: 'NOTDEFINED' } }),
  })

  writeRouteOccurrencePset(
    api,
    ifc,
    modelId,
    storeyContext.ownerHistory,
    routeElement,
    exportSegment,
    pipeLength,
    millimetresPerSourceUnit,
  )

  return { element: routeElement }
}

type RouteTypeGroup = {
  diameter: SanitaryPipeDiameterMm
  kind: string
  stackLabel: string
  exportSegment: SanitaryExportSegment
  ownerHistory: IfcHandle | null
  elements: IfcEntityRef[]
}

function routeTypeGroupKey(exportSegment: SanitaryExportSegment): string {
  return `${exportSegment.segment.pipeDiameterMm}|${exportSegment.segment.kind}|${exportSegment.riserStackLabel}`
}

// One shared PVC material is associated with every exported route element so Revit's
// material browser shows a single entry instead of one record per pipe segment.
function writeSharedRouteMaterial(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  elementHandles: IfcEntityRef[],
): void {
  if (elementHandles.length === 0) return

  const material = writeLabeledLine(api, modelId, 'route material', {
    expressID: -1,
    type: ifc.IFCMATERIAL,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'PVC'),
  })

  writeLabeledLine(api, modelId, 'route material relation', {
    expressID: -1,
    type: ifc.IFCRELASSOCIATESMATERIAL,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: null,
    Description: null,
    RelatedObjects: elementHandles.map((handle) => handleRef(handle.expressID)),
    RelatingMaterial: handleRef(material.expressID),
  })
}

// One IfcPipeSegmentType per (diameter, kind, stack) is shared across all matching
// occurrences (including those duplicated across riser-stack floors) instead of one per segment.
function writeSharedRoutePipeSegmentType(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  group: RouteTypeGroup,
  millimetresPerSourceUnit: number,
): void {
  const typeName = `BIMPipe ${diameterLabel(group.diameter)} Sanitary`
  const tag = `${group.stackLabel}-${group.diameter}-${group.kind}`

  const pipeSegmentType = writeLabeledLine(api, modelId, 'sanitary route pipe type', {
    expressID: -1,
    type: ifc.IFCPIPESEGMENTTYPE,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: group.ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, typeName),
    Description: null,
    ApplicableOccurrence: null,
    HasPropertySets: [],
    RepresentationMaps: null,
    Tag: api.CreateIfcType(modelId, ifc.IFCLABEL, `${tag}-Type`),
    ElementType: api.CreateIfcType(modelId, ifc.IFCLABEL, typeName),
    PredefinedType: { type: 3, value: 'RIGIDSEGMENT' },
  })

  writeLabeledLine(api, modelId, 'sanitary route type relation', {
    expressID: -1,
    type: ifc.IFCRELDEFINESBYTYPE,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: group.ownerHistory,
    Name: null,
    Description: null,
    RelatedObjects: group.elements.map((element) => handleRef(element.expressID)),
    RelatingType: handleRef(pipeSegmentType.expressID),
  })

  const typePset = writeRoutePipeTypeCommonPset(
    api,
    ifc,
    modelId,
    group.ownerHistory,
    pipeSegmentType,
    group.exportSegment,
    millimetresPerSourceUnit,
  )
  // The type is written first with empty HasPropertySets so the pset can reference it, then
  // re-written with the pset handle. web-ifc's WriteLine is an upsert keyed by expressID, so the
  // second call updates the existing line rather than creating a duplicate.
  pipeSegmentType.HasPropertySets = [handleRef(typePset.pset.expressID)]
  writeLabeledLine(api, modelId, 'sanitary route pipe type property sets', pipeSegmentType)
}

function writeRoutePipeTypeCommonPset(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  typeHandle: IfcEntityRef,
  exportSegment: SanitaryExportSegment,
  millimetresPerSourceUnit: number,
): { pset: IfcEntityRef; relation: IfcEntityRef } {
  const diameterMm = exportSegment.segment.pipeDiameterMm
  const diameterSource = diameterMm / millimetresPerSourceUnit
  const properties = [
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'NominalDiameter',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      diameterSource,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'OuterDiameter',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      diameterSource,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'Reference',
      api.GetTypeCodeFromName('IFCIDENTIFIER'),
      exportSegment.riserStackLabel,
    ),
  ]
  const pset = writePropertySet(api, ifc, modelId, ownerHistory, 'Pset_PipeSegmentTypeCommon', properties)
  const relation = writeRelDefinesByProperties(api, modelId, ownerHistory, [typeHandle], pset)
  return { pset, relation }
}

function writeRouteOccurrencePset(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  routeHandle: IfcEntityRef,
  exportSegment: SanitaryExportSegment,
  lengthSourceUnits: number,
  millimetresPerSourceUnit: number,
): void {
  const properties = [
    writePropertySingleValue(api, ifc, modelId, 'SystemType', api.GetTypeCodeFromName('IFCLABEL'), 'SANITARY'),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'Slope',
      api.GetTypeCodeFromName('IFCREAL'),
      exportSegment.slope,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'Length',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      lengthSourceUnits,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'NominalDiameter',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      exportSegment.segment.pipeDiameterMm / millimetresPerSourceUnit,
    ),
  ]
  const pset = writePropertySet(api, ifc, modelId, ownerHistory, 'Pset_FlowSegmentOccurrence', properties)
  writeRelDefinesByProperties(api, modelId, ownerHistory, [routeHandle], pset)
}

function appendToStoreyContainment(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  storeyContext: StoreyContext,
  elementExpressId: number,
  relationContainedInSpatialStructure: number,
): void {
  const createdHandle = handleRef(elementExpressId)
  if (storeyContext.containment) {
    if (!Array.isArray(storeyContext.containment.RelatedElements)) {
      storeyContext.containment.RelatedElements = []
    }
    storeyContext.containment.RelatedElements.push(createdHandle)
    api.WriteLine(modelId, storeyContext.containment)
    return
  }

  const relation = writeLabeledLine(api, modelId, 'sanitary route containment', {
    expressID: -1,
    type: relationContainedInSpatialStructure,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: storeyContext.ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe sanitary routes'),
    Description: null,
    RelatedElements: [createdHandle],
    RelatingStructure: handleRef(storeyContext.storeyId),
  })
  storeyContext.containment = relation as unknown as StoreyContext['containment']
}

function pickPerpendicularReference(axis: Vector3): Vector3 {
  const worldUp = new Vector3(0, 0, 1)
  const candidate = new Vector3().crossVectors(worldUp, axis)
  if (candidate.lengthSq() > 1e-9) return candidate.normalize()
  return new Vector3(1, 0, 0)
}

function writeDirection(api: IfcAPI, modelId: number, direction: Vector3): IfcEntityRef {
  return writeLabeledLine(api, modelId, 'direction', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCDIRECTION'),
    DirectionRatios: [direction.x, direction.y, direction.z],
  })
}

function writePropertySingleValue(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  propertyName: string,
  valueType: number,
  value: string | number,
): IfcEntityRef {
  return writeLabeledLine(api, modelId, `property ${propertyName}`, {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCPROPERTYSINGLEVALUE'),
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, propertyName),
    Description: null,
    NominalValue: api.CreateIfcType(modelId, valueType, value),
    Unit: null,
  })
}

function writePropertySet(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  name: string,
  properties: IfcEntityRef[],
): IfcEntityRef {
  return writeLabeledLine(api, modelId, `property set ${name}`, {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCPROPERTYSET'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, name),
    Description: null,
    HasProperties: properties.map((property) => handleRef(property.expressID)),
  })
}

function writeRelDefinesByProperties(
  api: IfcAPI,
  modelId: number,
  ownerHistory: IfcHandle | null,
  relatedObjects: IfcEntityRef[],
  propertySet: IfcEntityRef,
): IfcEntityRef {
  return writeLabeledLine(api, modelId, 'property relation', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELDEFINESBYPROPERTIES'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: null,
    Description: null,
    RelatedObjects: relatedObjects.map((object) => handleRef(object.expressID)),
    RelatingPropertyDefinition: handleRef(propertySet.expressID),
  })
}

function handleRef(expressId: number): IfcHandle {
  // web-ifc's WriteLine requires a real Handle instance for SELECT-typed attributes
  // (e.g. IfcLocalPlacement.RelativePlacement); a plain { type: 5, value } object throws
  // "Cannot pass non-string to std::string". A Handle instance is accepted everywhere.
  return new Handle(expressId) as unknown as IfcHandle
}

function writeLabeledLine(api: IfcAPI, modelId: number, label: string, line: IfcWritableLine) {
  try {
    api.WriteLine(modelId, line)
    return line
  } catch (error) {
    throw new Error(`Failed to write ${label}: ${error instanceof Error ? error.message : String(error)}`)
  }
}

export function createViewerPointToStoreyLocalResolver(
  api: IfcAPI,
  modelId: number,
  sourceUnitsPerViewerUnit: number,
): (
  storeyContext: StoreyContext,
  position: { x: number; y: number; z: number },
  elevationSourceUnits: number,
) => Vector3 {
  const inverseMatrixByPlacementId = new Map<number, Matrix4>()

  return (storeyContext, position, elevationSourceUnits) => {
    let inverseStoreyWorldMatrix = inverseMatrixByPlacementId.get(storeyContext.targetStoreyPlacementId)
    if (!inverseStoreyWorldMatrix) {
      const storeyWorldMatrix = resolveLocalPlacementWorldMatrix(api, modelId, storeyContext.targetStoreyPlacementId)
      inverseStoreyWorldMatrix = storeyWorldMatrix.clone().invert()
      inverseMatrixByPlacementId.set(storeyContext.targetStoreyPlacementId, inverseStoreyWorldMatrix)
    }
    // Viewer XZ are the plan axes; viewer Y is the up-axis (elevation).
    // Elevation is re-derived from storeyElevation + slope (elevationSourceUnits) rather than
    // reading position.y, so position.y is intentionally ignored here — duplicated routes carry a
    // non-zero y delta for per-floor display offsets that must not leak into the exported geometry.
    const ifcWorldPoint = new Vector3(
      position.x * sourceUnitsPerViewerUnit,
      -position.z * sourceUnitsPerViewerUnit,
      elevationSourceUnits,
    )
    return ifcWorldPoint.clone().applyMatrix4(inverseStoreyWorldMatrix)
  }
}

