import { Matrix4, Vector3 } from 'three'
import type { IfcAPI } from 'web-ifc'
import type { Riser, Storey, StoreyId } from '@/domain/types'
import type { SanitaryFixtureRoute } from '@/shared/routes/buildSanitaryRoutes'
import {
  collectSanitaryExportSegments,
  diameterLabel,
  segmentEndpointElevationsSourceUnits,
  type SanitaryExportSegment,
} from '@/shared/routes/sanitaryRouteExportPlan'

type IfcHandle = { type: 5; value: number }
type IfcWritableLine = { expressID: number; type: number; [key: string]: unknown }
type IfcEntityRef = { expressID: number; type: number }
type ImportedIfcTypes = Awaited<typeof import('web-ifc')>

type StoreyContext = {
  storeyId: StoreyId
  targetStoreyPlacementId: number
  ownerHistory: IfcHandle | null
  containment: {
    expressID: number
    type: number
    RelatedElements?: unknown[]
    RelatingStructure?: IfcHandle | null
  } | null
}

export type WrittenSanitaryRoute = {
  element: IfcEntityRef
  exportSegment: SanitaryExportSegment
}

const SANITARY_ROUTE_SYSTEM_NAME = 'BIMPipe Sanitary Routes'
const SANITARY_ROUTE_SYSTEM_DESCRIPTION = 'Sanitary fixture routes generated by BIMPipe for investor demo.'

export function writeSanitaryRouteElements(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  schema: string,
  bodyContextId: number,
  routes: SanitaryFixtureRoute[],
  storeys: Pick<Storey, 'id' | 'elevation'>[],
  risers: Riser[],
  sourceUnitsPerViewerUnit: number,
  millimetresPerSourceUnit: number,
  resolveStoreyContext: (storeyId: StoreyId) => StoreyContext,
  resolveViewerPointToStoreyLocal: (
    storeyContext: StoreyContext,
    position: { x: number; y: number; z: number },
    elevationSourceUnits: number,
  ) => Vector3,
  relationContainedInSpatialStructure: number,
): { elements: WrittenSanitaryRoute[]; flowSegmentHandles: IfcHandle[] } {
  const exportSegments = collectSanitaryExportSegments(routes, storeys, risers)
  if (exportSegments.length === 0) {
    return { elements: [], flowSegmentHandles: [] }
  }

  const storeyElevationById = new Map(storeys.map((storey) => [storey.id, storey.elevation]))
  const elements: WrittenSanitaryRoute[] = []
  const flowSegmentHandles: IfcHandle[] = []
  const containmentByStorey = new Map<StoreyId, StoreyContext['containment']>()

  for (const exportSegment of exportSegments) {
    const storeyElevation = storeyElevationById.get(exportSegment.storeyId)
    if (typeof storeyElevation !== 'number' || !Number.isFinite(storeyElevation)) continue

    const storeyContext = resolveStoreyContext(exportSegment.storeyId)
    const { startElevation, endElevation } = segmentEndpointElevationsSourceUnits(
      exportSegment,
      storeyElevation,
      sourceUnitsPerViewerUnit,
      millimetresPerSourceUnit,
    )

    const startLocal = resolveViewerPointToStoreyLocal(
      storeyContext,
      exportSegment.segment.from,
      startElevation,
    )
    const endLocal = resolveViewerPointToStoreyLocal(
      storeyContext,
      exportSegment.segment.to,
      endElevation,
    )

    const written = writeSlopedPipeSegment(
      api,
      ifc,
      modelId,
      schema,
      bodyContextId,
      storeyContext,
      exportSegment,
      startLocal,
      endLocal,
      millimetresPerSourceUnit,
    )

    elements.push({ element: written.element, exportSegment })
    flowSegmentHandles.push(handleRef(written.element.expressID))

    if (!containmentByStorey.has(exportSegment.storeyId)) {
      containmentByStorey.set(exportSegment.storeyId, storeyContext.containment)
    }
    appendToStoreyContainment(
      api,
      ifc,
      modelId,
      storeyContext,
      written.element.expressID,
      relationContainedInSpatialStructure,
    )
  }

  return { elements, flowSegmentHandles }
}

export function writeSanitaryRouteSystemAssignment(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  routeHandles: IfcHandle[],
): void {
  if (routeHandles.length === 0) return

  const buildingType = api.GetTypeCodeFromName('IFCBUILDING')
  const buildingIds = api.GetLineIDsWithType(modelId, buildingType)
  if (buildingIds.size() === 0) {
    throw new Error('Source IFC has no IfcBuilding; cannot attach BIMPipe sanitary route system.')
  }

  const buildingId = buildingIds.get(0)
  const system = writeLabeledLine(api, modelId, 'sanitary route system', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCSYSTEM'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, SANITARY_ROUTE_SYSTEM_NAME),
    Description: api.CreateIfcType(
      modelId,
      api.GetTypeCodeFromName('IFCTEXT'),
      SANITARY_ROUTE_SYSTEM_DESCRIPTION,
    ),
    ObjectType: api.CreateIfcType(modelId, ifc.IFCLABEL, 'SANITARY'),
  })

  writeLabeledLine(api, modelId, 'sanitary route system assignment', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELASSIGNSTOGROUP'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe Sanitary Route Assignment'),
    Description: null,
    RelatedObjects: routeHandles,
    RelatedObjectsType: api.CreateIfcType(modelId, ifc.IFCLABEL, 'IFCFLOWSEGMENT'),
    RelatingGroup: handleRef(system.expressID),
  })

  writeLabeledLine(api, modelId, 'sanitary route system service', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELSERVICESBUILDINGS'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe Sanitary Route Service'),
    Description: null,
    RelatedBuildings: [handleRef(buildingId)],
    RelatingSystem: handleRef(system.expressID),
  })
}

function writeSlopedPipeSegment(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  schema: string,
  bodyContextId: number,
  storeyContext: StoreyContext,
  exportSegment: SanitaryExportSegment,
  startLocal: Vector3,
  endLocal: Vector3,
  millimetresPerSourceUnit: number,
): { element: IfcEntityRef } {
  const {
    IFCAXIS2PLACEMENT2D,
    IFCAXIS2PLACEMENT3D,
    IFCCARTESIANPOINT,
    IFCCIRCLEPROFILEDEF,
    IFCEXTRUDEDAREASOLID,
    IFCFLOWSEGMENT,
    IFCIDENTIFIER,
    IFCLABEL,
    IFCLENGTHMEASURE,
    IFCLOCALPLACEMENT,
    IFCMATERIAL,
    IFCPIPESEGMENT,
    IFCPIPESEGMENTTYPE,
    IFCPRODUCTDEFINITIONSHAPE,
    IFCRELASSOCIATESMATERIAL,
    IFCRELDEFINESBYTYPE,
    IFCSHAPEREPRESENTATION,
  } = ifc

  const pipeVector = endLocal.clone().sub(startLocal)
  const pipeLength = pipeVector.length()
  if (!Number.isFinite(pipeLength) || pipeLength <= 1e-6) {
    throw new Error(`Sanitary route segment ${exportSegment.key} resolved zero length.`)
  }

  const pipeAxis = pipeVector.clone().normalize()
  const radiusSourceUnits =
    (exportSegment.segment.pipeDiameterMm / 2) / millimetresPerSourceUnit

  const point2d = writeLabeledLine(api, modelId, 'route profile point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
    ],
  })

  const dir2d = writeLabeledLine(api, modelId, 'route profile direction', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCDIRECTION'),
    DirectionRatios: [1, 0],
  })

  const profilePlacement = writeLabeledLine(api, modelId, 'route profile placement', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT2D,
    Location: handleRef(point2d.expressID),
    RefDirection: handleRef(dir2d.expressID),
  })

  const profile = writeLabeledLine(api, modelId, 'route circle profile', {
    expressID: -1,
    type: IFCCIRCLEPROFILEDEF,
    ProfileType: { type: 3, value: 'AREA' },
    ProfileName: null,
    Position: handleRef(profilePlacement.expressID),
    Radius: api.CreateIfcType(modelId, IFCLENGTHMEASURE, radiusSourceUnits),
  })

  const point3d = writeLabeledLine(api, modelId, 'route swept solid point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, 0),
    ],
  })

  const extrusionDirection = writeDirection(api, modelId, pipeAxis)
  const refDirection = pickPerpendicularReference(pipeAxis)
  const profileZAxis = writeDirection(api, modelId, refDirection)

  const sweptPlacement = writeLabeledLine(api, modelId, 'route swept solid placement', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT3D,
    Location: handleRef(point3d.expressID),
    Axis: handleRef(profileZAxis.expressID),
    RefDirection: handleRef(extrusionDirection.expressID),
  })

  const solid = writeLabeledLine(api, modelId, 'route extruded solid', {
    expressID: -1,
    type: IFCEXTRUDEDAREASOLID,
    SweptArea: handleRef(profile.expressID),
    Position: handleRef(sweptPlacement.expressID),
    ExtrudedDirection: handleRef(extrusionDirection.expressID),
    Depth: api.CreateIfcType(modelId, IFCLENGTHMEASURE, pipeLength),
  })

  const shape = writeLabeledLine(api, modelId, 'route shape representation', {
    expressID: -1,
    type: IFCSHAPEREPRESENTATION,
    ContextOfItems: handleRef(bodyContextId),
    RepresentationIdentifier: api.CreateIfcType(modelId, IFCLABEL, 'Body'),
    RepresentationType: api.CreateIfcType(modelId, IFCLABEL, 'SweptSolid'),
    Items: [handleRef(solid.expressID)],
  })

  const productShape = writeLabeledLine(api, modelId, 'route product definition shape', {
    expressID: -1,
    type: IFCPRODUCTDEFINITIONSHAPE,
    Name: null,
    Description: null,
    Representations: [handleRef(shape.expressID)],
  })

  const placementPoint = writeLabeledLine(api, modelId, 'route object placement point', {
    expressID: -1,
    type: IFCCARTESIANPOINT,
    Coordinates: [
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, startLocal.x),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, startLocal.y),
      api.CreateIfcType(modelId, IFCLENGTHMEASURE, startLocal.z),
    ],
  })

  const placementAxis = writeLabeledLine(api, modelId, 'route object placement axis', {
    expressID: -1,
    type: IFCAXIS2PLACEMENT3D,
    Location: handleRef(placementPoint.expressID),
    Axis: handleRef(profileZAxis.expressID),
    RefDirection: handleRef(extrusionDirection.expressID),
  })

  const targetStoreyPlacement = api.GetLine(modelId, storeyContext.targetStoreyPlacementId, false)
  const localPlacement = createLabeledEntity(
    api,
    modelId,
    'route local placement',
    IFCLOCALPLACEMENT,
    targetStoreyPlacement,
    placementAxis,
  )
  api.WriteLine(modelId, localPlacement)

  const diameter = exportSegment.segment.pipeDiameterMm
  const typeName = `BIMPipe ${diameterLabel(diameter)} Sanitary`
  const routeElementType = schema === 'IFC2X3' ? IFCFLOWSEGMENT : IFCPIPESEGMENT
  const tag = `${exportSegment.riserStackLabel}-${diameter}-${exportSegment.segment.kind}`

  const routeElement = writeLabeledLine(api, modelId, 'sanitary route element', {
    expressID: -1,
    type: routeElementType,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: storeyContext.ownerHistory,
    Name: api.CreateIfcType(modelId, IFCLABEL, exportSegment.label),
    Description: api.CreateIfcType(
      modelId,
      IFCLABEL,
      `Sanitary ${exportSegment.segment.kind} route; ${(exportSegment.slope * 100).toFixed(1)}% slope toward riser.`,
    ),
    ObjectType: api.CreateIfcType(modelId, IFCLABEL, 'BIMPipeSanitaryRoute'),
    ObjectPlacement: handleRef(localPlacement.expressID),
    Representation: handleRef(productShape.expressID),
    Tag: api.CreateIfcType(modelId, IFCIDENTIFIER, tag),
    ...(schema === 'IFC2X3' ? {} : { PredefinedType: { type: 3, value: 'NOTDEFINED' } }),
  })

  if (schema === 'IFC2X3') {
    const pipeSegmentType = writeLabeledLine(api, modelId, 'sanitary route pipe type', {
      expressID: -1,
      type: IFCPIPESEGMENTTYPE,
      GlobalId: api.CreateIFCGloballyUniqueId(modelId),
      OwnerHistory: storeyContext.ownerHistory,
      Name: api.CreateIfcType(modelId, IFCLABEL, typeName),
      Description: null,
      ApplicableOccurrence: null,
      HasPropertySets: [],
      RepresentationMaps: null,
      Tag: api.CreateIfcType(modelId, IFCLABEL, `${tag}-Type`),
      ElementType: api.CreateIfcType(modelId, IFCLABEL, typeName),
      PredefinedType: { type: 3, value: 'RIGIDSEGMENT' },
    })

    writeLabeledLine(api, modelId, 'sanitary route type relation', {
      expressID: -1,
      type: IFCRELDEFINESBYTYPE,
      GlobalId: api.CreateIFCGloballyUniqueId(modelId),
      OwnerHistory: storeyContext.ownerHistory,
      Name: null,
      Description: null,
      RelatedObjects: [handleRef(routeElement.expressID)],
      RelatingType: handleRef(pipeSegmentType.expressID),
    })

    const typePset = writeRoutePipeTypeCommonPset(
      api,
      ifc,
      modelId,
      storeyContext.ownerHistory,
      pipeSegmentType,
      exportSegment,
      millimetresPerSourceUnit,
    )
    pipeSegmentType.HasPropertySets = [handleRef(typePset.pset.expressID)]
    writeLabeledLine(api, modelId, 'sanitary route pipe type property sets', pipeSegmentType)
  }

  const material = writeLabeledLine(api, modelId, 'route material', {
    expressID: -1,
    type: IFCMATERIAL,
    Name: api.CreateIfcType(modelId, IFCLABEL, 'PVC'),
  })

  writeLabeledLine(api, modelId, 'route material relation', {
    expressID: -1,
    type: IFCRELASSOCIATESMATERIAL,
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: storeyContext.ownerHistory,
    Name: null,
    Description: null,
    RelatedObjects: [handleRef(routeElement.expressID)],
    RelatingMaterial: material,
  })

  writeRouteOccurrencePset(api, ifc, modelId, storeyContext.ownerHistory, routeElement, exportSegment, pipeLength)

  return { element: routeElement }
}

function writeRoutePipeTypeCommonPset(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  typeHandle: IfcEntityRef,
  exportSegment: SanitaryExportSegment,
  millimetresPerSourceUnit: number,
): { pset: IfcEntityRef; relation: IfcEntityRef } {
  const diameterMm = exportSegment.segment.pipeDiameterMm
  const diameterSource = diameterMm / millimetresPerSourceUnit
  const properties = [
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'NominalDiameter',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      diameterSource,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'OuterDiameter',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      diameterSource,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'Reference',
      api.GetTypeCodeFromName('IFCIDENTIFIER'),
      exportSegment.riserStackLabel,
    ),
  ]
  const pset = writePropertySet(api, ifc, modelId, ownerHistory, 'Pset_PipeSegmentTypeCommon', properties)
  const relation = writeRelDefinesByProperties(api, modelId, ownerHistory, [typeHandle], pset)
  return { pset, relation }
}

function writeRouteOccurrencePset(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  routeHandle: IfcEntityRef,
  exportSegment: SanitaryExportSegment,
  lengthSourceUnits: number,
): void {
  const properties = [
    writePropertySingleValue(api, ifc, modelId, 'SystemType', api.GetTypeCodeFromName('IFCLABEL'), 'SANITARY'),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'Slope',
      api.GetTypeCodeFromName('IFCREAL'),
      exportSegment.slope,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'Length',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      lengthSourceUnits,
    ),
    writePropertySingleValue(
      api,
      ifc,
      modelId,
      'NominalDiameter',
      api.GetTypeCodeFromName('IFCPOSITIVELENGTHMEASURE'),
      exportSegment.segment.pipeDiameterMm,
    ),
  ]
  const pset = writePropertySet(api, ifc, modelId, ownerHistory, 'Pset_FlowSegmentOccurrence', properties)
  writeRelDefinesByProperties(api, modelId, ownerHistory, [routeHandle], pset)
}

function appendToStoreyContainment(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  storeyContext: StoreyContext,
  elementExpressId: number,
  relationContainedInSpatialStructure: number,
): void {
  const createdHandle = handleRef(elementExpressId)
  if (storeyContext.containment) {
    storeyContext.containment.RelatedElements = [
      ...(Array.isArray(storeyContext.containment.RelatedElements)
        ? storeyContext.containment.RelatedElements
        : []),
      createdHandle,
    ]
    api.WriteLine(modelId, storeyContext.containment)
    return
  }

  const relation = api.CreateIfcEntity(
    modelId,
    relationContainedInSpatialStructure,
    api.CreateIFCGloballyUniqueId(modelId),
    storeyContext.ownerHistory,
    api.CreateIfcType(modelId, ifc.IFCLABEL, 'BIMPipe sanitary routes'),
    null,
    [createdHandle],
    handleRef(storeyContext.storeyId),
  )
  api.WriteLine(modelId, relation)
  storeyContext.containment = relation as StoreyContext['containment']
}

function pickPerpendicularReference(axis: Vector3): Vector3 {
  const worldUp = new Vector3(0, 0, 1)
  const candidate = new Vector3().crossVectors(worldUp, axis)
  if (candidate.lengthSq() > 1e-9) return candidate.normalize()
  return new Vector3(1, 0, 0)
}

function writeDirection(api: IfcAPI, modelId: number, direction: Vector3): IfcEntityRef {
  return writeLabeledLine(api, modelId, 'direction', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCDIRECTION'),
    DirectionRatios: [direction.x, direction.y, direction.z],
  })
}

function writePropertySingleValue(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  propertyName: string,
  valueType: number,
  value: string | number,
): IfcEntityRef {
  return writeLabeledLine(api, modelId, `property ${propertyName}`, {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCPROPERTYSINGLEVALUE'),
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, propertyName),
    Description: null,
    NominalValue: api.CreateIfcType(modelId, valueType, value),
    Unit: null,
  })
}

function writePropertySet(
  api: IfcAPI,
  ifc: ImportedIfcTypes,
  modelId: number,
  ownerHistory: IfcHandle | null,
  name: string,
  properties: IfcEntityRef[],
): IfcEntityRef {
  return writeLabeledLine(api, modelId, `property set ${name}`, {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCPROPERTYSET'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: api.CreateIfcType(modelId, ifc.IFCLABEL, name),
    Description: null,
    HasProperties: properties.map((property) => handleRef(property.expressID)),
  })
}

function writeRelDefinesByProperties(
  api: IfcAPI,
  modelId: number,
  ownerHistory: IfcHandle | null,
  relatedObjects: IfcEntityRef[],
  propertySet: IfcEntityRef,
): IfcEntityRef {
  return writeLabeledLine(api, modelId, 'property relation', {
    expressID: -1,
    type: api.GetTypeCodeFromName('IFCRELDEFINESBYPROPERTIES'),
    GlobalId: api.CreateIFCGloballyUniqueId(modelId),
    OwnerHistory: ownerHistory,
    Name: null,
    Description: null,
    RelatedObjects: relatedObjects.map((object) => handleRef(object.expressID)),
    RelatingPropertyDefinition: handleRef(propertySet.expressID),
  })
}

function handleRef(expressId: number): IfcHandle {
  return { type: 5, value: expressId }
}

function writeLabeledLine(api: IfcAPI, modelId: number, label: string, line: IfcWritableLine) {
  try {
    api.WriteLine(modelId, line)
    return line
  } catch (error) {
    throw new Error(`Failed to write ${label}: ${error instanceof Error ? error.message : String(error)}`)
  }
}

function createLabeledEntity(api: IfcAPI, modelId: number, label: string, type: number, ...args: unknown[]) {
  try {
    return api.CreateIfcEntity(modelId, type, ...args) as { expressID: number; type: number }
  } catch (error) {
    throw new Error(`Failed to create ${label}: ${error instanceof Error ? error.message : String(error)}`)
  }
}

export function createViewerPointToStoreyLocalResolver(
  api: IfcAPI,
  modelId: number,
  sourceUnitsPerViewerUnit: number,
): (
  storeyContext: StoreyContext,
  position: { x: number; y: number; z: number },
  elevationSourceUnits: number,
) => Vector3 {
  return (storeyContext, position, elevationSourceUnits) => {
    const storeyWorldMatrix = resolveLocalPlacementWorldMatrix(api, modelId, storeyContext.targetStoreyPlacementId)
    const inverseStoreyWorldMatrix = storeyWorldMatrix.clone().invert()
    const ifcWorldPoint = new Vector3(
      position.x * sourceUnitsPerViewerUnit,
      -position.z * sourceUnitsPerViewerUnit,
      elevationSourceUnits,
    )
    return ifcWorldPoint.clone().applyMatrix4(inverseStoreyWorldMatrix)
  }
}

function resolveLocalPlacementWorldMatrix(api: IfcAPI, modelId: number, placementId: number): Matrix4 {
  const placement = api.GetLine(modelId, placementId, false) as {
    PlacementRelTo?: IfcHandle | null
    RelativePlacement?: IfcHandle | null
  } | null
  if (!placement) throw new Error(`Missing IfcLocalPlacement #${placementId}.`)

  const parentMatrix =
    placement.PlacementRelTo?.value != null
      ? resolveLocalPlacementWorldMatrix(api, modelId, placement.PlacementRelTo.value)
      : new Matrix4()

  const relativePlacementId = placement.RelativePlacement?.value ?? null
  if (relativePlacementId === null) return parentMatrix

  return parentMatrix.multiply(resolveAxisPlacementMatrix(api, modelId, relativePlacementId))
}

function resolveAxisPlacementMatrix(api: IfcAPI, modelId: number, placementId: number): Matrix4 {
  const placement = api.GetLine(modelId, placementId, false) as {
    Location?: IfcHandle | null
    Axis?: IfcHandle | null
    RefDirection?: IfcHandle | null
  } | null
  if (!placement) throw new Error(`Missing axis placement #${placementId}.`)

  const location = readCoordinates(api, modelId, placement.Location?.value ?? null, [0, 0, 0])
  const zAxis = readDirection(api, modelId, placement.Axis?.value ?? null, new Vector3(0, 0, 1))
  const xHint = readDirection(api, modelId, placement.RefDirection?.value ?? null, new Vector3(1, 0, 0))
  const yAxis = new Vector3().crossVectors(zAxis, xHint).normalize()
  const xAxis = new Vector3().crossVectors(yAxis, zAxis).normalize()

  const matrix = new Matrix4()
  matrix.makeBasis(xAxis, yAxis, zAxis)
  matrix.setPosition(location)
  return matrix
}

function readCoordinates(
  api: IfcAPI,
  modelId: number,
  pointId: number | null,
  fallback: [number, number, number],
): Vector3 {
  if (pointId === null) return new Vector3(...fallback)
  const point = api.GetLine(modelId, pointId, false) as {
    Coordinates?: Array<{ value?: number } | number> | null
  } | null
  const coords = (point?.Coordinates ?? []).map((value) => Number((value as { value?: number })?.value ?? value))
  return new Vector3(
    Number.isFinite(coords[0]) ? coords[0] : fallback[0],
    Number.isFinite(coords[1]) ? coords[1] : fallback[1],
    Number.isFinite(coords[2]) ? coords[2] : fallback[2],
  )
}

function readDirection(
  api: IfcAPI,
  modelId: number,
  directionId: number | null,
  fallback: Vector3,
): Vector3 {
  if (directionId === null) return fallback.clone()
  const direction = api.GetLine(modelId, directionId, false) as {
    DirectionRatios?: Array<{ value?: number } | number> | null
  } | null
  const ratios = (direction?.DirectionRatios ?? []).map((value) =>
    Number((value as { value?: number })?.value ?? value),
  )
  const vector = new Vector3(
    Number.isFinite(ratios[0]) ? ratios[0] : fallback.x,
    Number.isFinite(ratios[1]) ? ratios[1] : fallback.y,
    Number.isFinite(ratios[2]) ? ratios[2] : fallback.z,
  )
  return vector.lengthSq() > 1e-9 ? vector.normalize() : fallback.clone()
}
