import { describe, expect, it, vi } from 'vitest'
import { exportIfcWithRisers } from './exportIfcWithRisers'
import type { Riser } from '@/domain/types'
import type { IfcAPI, RawLineData } from 'web-ifc'

vi.mock('web-ifc', () => ({
  IFCAXIS2PLACEMENT3D: 1,
  IFCBUILDINGELEMENTPROXY: 2,
  IFCCARTESIANPOINT: 3,
  IFCIDENTIFIER: 4,
  IFCLABEL: 5,
  IFCLOCALPLACEMENT: 6,
  IFCPROJECT: 8,
  IFCRELAGGREGATES: 9,
  IFCRELCONTAINEDINSPATIALSTRUCTURE: 7,
}))

function makeIdVector(values: number[]) {
  return {
    size: () => values.length,
    get: (index: number) => values[index],
  }
}

describe('exportIfcWithRisers', () => {
  it('creates a new plumbing-only IFC seeded from the source spatial context and preserves stack labels', async () => {
    const sourceModelId = 77
    const plumbingModelId = 88
    const rawLines = new Map<number, RawLineData>([
      [1, {
        ID: 1,
        type: 8,
        arguments: [
          { type: 1, value: 'guid-project' },
          null,
          { type: 1, value: 'Source Project' },
          null,
          null,
          null,
          [{ type: 5, value: 501 }],
          { type: 5, value: 601 },
        ],
      }],
      [2, {
        ID: 2,
        type: 100,
        arguments: [
          { type: 1, value: 'guid-storey-2' },
          { type: 5, value: 99 },
          { type: 1, value: 'Level 2' },
          null,
          null,
          { type: 5, value: 701 },
        ],
      }],
      [3, {
        ID: 3,
        type: 100,
        arguments: [
          { type: 1, value: 'guid-storey-3' },
          { type: 5, value: 99 },
          { type: 1, value: 'Level 3' },
          null,
          null,
          { type: 5, value: 702 },
        ],
      }],
      [9, {
        ID: 9,
        type: 9,
        arguments: [
          { type: 1, value: 'guid-rel' },
          null,
          { type: 1, value: 'Project decomposition' },
          null,
          { type: 5, value: 1 },
          [{ type: 5, value: 2 }, { type: 5, value: 3 }],
        ],
      }],
      [99, { ID: 99, type: 200, arguments: [] }],
      [501, { ID: 501, type: 201, arguments: [] }],
      [601, { ID: 601, type: 202, arguments: [] }],
      [701, { ID: 701, type: 203, arguments: [] }],
      [702, { ID: 702, type: 203, arguments: [] }],
    ])

    const api = {
      OpenModel: vi.fn(() => sourceModelId),
      CreateModel: vi.fn(() => plumbingModelId),
      CloseModel: vi.fn(),
      GetModelSchema: vi.fn(() => 'IFC4'),
      GetRawLineData: vi.fn((_modelId: number, expressId: number) => rawLines.get(expressId)!),
      WriteRawLineData: vi.fn(),
      SaveModel: vi.fn(() => new Uint8Array([9, 8, 7])),
      CreateIFCGloballyUniqueId: vi.fn(() => 'guid-new'),
      CreateIfcType: vi.fn((modelId: number, type: number, value: string) => ({
        modelId,
        type,
        value,
      })),
      CreateIfcEntity: vi.fn((modelId: number, type: number, ...args: unknown[]) => ({
        modelId,
        type,
        args,
      })),
      WriteLine: vi.fn(),
      GetLineIDsWithType: vi.fn((modelId: number, type: number) => {
        if (modelId === sourceModelId && type === 9) return makeIdVector([9])
        if (modelId === sourceModelId && type === 8) return makeIdVector([1])
        if (modelId === plumbingModelId && type === 7) return makeIdVector([])
        return makeIdVector([])
      }),
      GetLine: vi.fn((modelId: number, expressId: number) => {
        if (modelId === sourceModelId && expressId === 9) {
          return {
            RelatingObject: { type: 5, value: 1 },
            RelatedObjects: [{ type: 5, value: 2 }, { type: 5, value: 3 }],
          }
        }
        if (modelId === plumbingModelId && (expressId === 2 || expressId === 3)) {
          return { OwnerHistory: { type: 5, value: 99 } }
        }
        return null
      }),
    } as unknown as IfcAPI

    const risers: Riser[] = [
      { id: 'a-2', stackId: 'stack-a', stackLabel: 'R12', storeyId: 2, position: { x: 10, y: 612, z: 20 } },
      { id: 'b-2', stackId: 'stack-b', stackLabel: 'R7', storeyId: 2, position: { x: 30, y: 612, z: 40 } },
      { id: 'a-3', stackId: 'stack-a', stackLabel: 'R12', storeyId: 3, position: { x: 10, y: 918, z: 20 } },
      { id: 'b-3', stackId: 'stack-b', stackLabel: 'R7', storeyId: 3, position: { x: 30, y: 918, z: 40 } },
    ]

    const result = await exportIfcWithRisers(api, new Uint8Array([1, 2, 3]), 2, risers)

    expect(result).toEqual(new Uint8Array([9, 8, 7]))
    expect(api.CreateModel).toHaveBeenCalledWith({
      schema: 'IFC4',
      name: 'BIMPipe Plumbing',
      description: ['Plumbing-only IFC generated from BIMPipe riser layout'],
      authors: ['BIMPipe'],
      organizations: ['BIMPipe'],
      authorization: 'Generated by BIMPipe',
    })

    const copiedLineIds = (api.WriteRawLineData as ReturnType<typeof vi.fn>).mock.calls
      .map((call) => call[1].ID)
      .sort((left, right) => left - right)
    expect(copiedLineIds).toEqual([1, 2, 3, 9, 99, 501, 601, 701, 702])

    const identifierValues = (api.CreateIfcType as ReturnType<typeof vi.fn>).mock.calls
      .filter((call) => call[1] === 4)
      .map((call) => call[2])

    expect(identifierValues).toEqual(['R12', 'R7', 'R12', 'R7'])
    expect(api.CloseModel).toHaveBeenCalledWith(plumbingModelId)
    expect(api.CloseModel).toHaveBeenCalledWith(sourceModelId)
  })
})
