import type { IfcAPI } from 'web-ifc'
import type { Riser, StoreyId } from '@/domain/types'
import type { RawLineData } from 'web-ifc'

type IfcHandle = { type: 5; value: number }

export async function exportIfcWithRisers(
  api: IfcAPI,
  sourceBytes: Uint8Array,
  primaryStoreyId: StoreyId,
  risers: Riser[],
): Promise<Uint8Array> {
  if (risers.length === 0) {
    throw new Error('Add or suggest risers before downloading the plumbing IFC.')
  }

  const {
    IFCAXIS2PLACEMENT3D,
    IFCBUILDINGELEMENTPROXY,
    IFCCARTESIANPOINT,
    IFCIDENTIFIER,
    IFCLABEL,
    IFCLENGTHMEASURE,
    IFCLOCALPLACEMENT,
    IFCPROJECT,
    IFCRELAGGREGATES,
    IFCRELCONTAINEDINSPATIALSTRUCTURE,
    IFCTEXT,
  } = await import('web-ifc')

  const sourceModelId = api.OpenModel(sourceBytes.slice())
  let plumbingModelId: number | null = null

  try {
    const schema = api.GetModelSchema(sourceModelId)
    plumbingModelId = api.CreateModel({
      schema,
      name: 'BIMPipe Plumbing',
      description: ['Plumbing-only IFC generated from BIMPipe riser layout'],
      authors: ['BIMPipe'],
      organizations: ['BIMPipe'],
      authorization: 'Generated by BIMPipe',
    })
    const modelId = plumbingModelId

    const contextLineIds = collectSpatialContextLineIds(
      api,
      sourceModelId,
      primaryStoreyId,
      risers,
      IFCRELAGGREGATES,
      IFCPROJECT,
    )
    const rawLines = collectRawLineClosure(api, sourceModelId, contextLineIds)
    for (const rawLine of rawLines) {
      try {
        api.WriteRawLineData(modelId, rawLine)
      } catch {
        // Some raw lines (e.g. geometry primitives) carry WASM-internal argument
        // objects that cannot be serialised into a different model; skip them.
        // The spatial hierarchy and owner-history lines that matter will succeed.
      }
    }

    // Resolve owner history from the source storey (used for all new entities).
    // Read from sourceModelId — the storey line may not survive WriteRawLineData on all IFC files.
    const primaryStorey = api.GetLine(sourceModelId, primaryStoreyId, false) as {
      OwnerHistory?: IfcHandle | null
    } | null

    if (!primaryStorey) {
      throw new Error(`Storey #${primaryStoreyId} is missing from the IFC model.`)
    }

    const ownerHistory = resolveCopiedOwnerHistoryHandle(
      api,
      sourceModelId,
      modelId,
      primaryStoreyId,
    )

    // Group risers by storeyId so each floor gets its own containment entry.
    const risersByStorey = new Map<StoreyId, Riser[]>()
    for (const riser of risers) {
      const group = risersByStorey.get(riser.storeyId) ?? []
      group.push(riser)
      risersByStorey.set(riser.storeyId, group)
    }

    for (const [storeyId, storeyRisers] of risersByStorey) {
      const riserElements = storeyRisers.map((riser, index) =>
        createRiserElement(
          api,
          modelId,
          schema,
          ownerHistory,
          riser.stackLabel.trim() || `R${index + 1}`,
          riser.position,
        ),
      )

      const containment = findStoreyContainmentRelation(
        api,
        modelId,
        IFCRELCONTAINEDINSPATIALSTRUCTURE,
        storeyId,
      )

      if (containment) {
        containment.RelatedElements = [
          ...(Array.isArray(containment.RelatedElements) ? containment.RelatedElements : []),
          ...riserElements,
        ]
        api.WriteLine(modelId, containment)
      } else {
        const relation = api.CreateIfcEntity(
          modelId,
          IFCRELCONTAINEDINSPATIALSTRUCTURE,
          api.CreateIFCGloballyUniqueId(modelId),
          ownerHistory,
          api.CreateIfcType(modelId, IFCLABEL, 'BIMPipe riser set'),
          null,
          riserElements,
          handleRef(storeyId),
        )
        api.WriteLine(modelId, relation)
      }
    }

    return api.SaveModel(modelId)
  } finally {
    if (plumbingModelId !== null) {
      api.CloseModel(plumbingModelId)
    }
    api.CloseModel(sourceModelId)
  }

  function createRiserElement(
    localApi: IfcAPI,
    modelId: number,
    _schema: string,
    ownerHistory: IfcHandle | null,
    tag: string,
    position: { x: number; y: number; z: number },
  ): IfcHandle {
    // Write entities bottom-up so each gets an expressID before being referenced.
    const point = localApi.CreateIfcEntity(modelId, IFCCARTESIANPOINT, [
      localApi.CreateIfcType(modelId, IFCLENGTHMEASURE, position.x),
      localApi.CreateIfcType(modelId, IFCLENGTHMEASURE, position.y),
      localApi.CreateIfcType(modelId, IFCLENGTHMEASURE, position.z),
    ])
    localApi.WriteLine(modelId, point)

    const axisPlacement = localApi.CreateIfcEntity(
      modelId, IFCAXIS2PLACEMENT3D,
      handleRef(point.expressID), null, null,
    )
    localApi.WriteLine(modelId, axisPlacement)

    const localPlacement = localApi.CreateIfcEntity(
      modelId, IFCLOCALPLACEMENT,
      null, axisPlacement,
    )
    localApi.WriteLine(modelId, localPlacement)

    const name = localApi.CreateIfcType(modelId, IFCLABEL, `BIMPipe ${tag}`)
    const description = localApi.CreateIfcType(
      modelId,
      IFCTEXT,
      `Vertical riser marker placed by BIMPipe at (${position.x.toFixed(3)}, ${position.z.toFixed(3)})`,
    )
    const objectType = localApi.CreateIfcType(modelId, IFCLABEL, 'BIMPipeRiser')
    const identifier = localApi.CreateIfcType(modelId, IFCIDENTIFIER, tag)

    const riserElement = localApi.CreateIfcEntity(
      modelId,
      IFCBUILDINGELEMENTPROXY,
      localApi.CreateIFCGloballyUniqueId(modelId),
      ownerHistory,
      name,
      description,
      objectType,
      localPlacement,
      null,
      identifier,
      null,
    )
    localApi.WriteLine(modelId, riserElement)

    return handleRef(riserElement.expressID)
  }
}

function collectSpatialContextLineIds(
  api: IfcAPI,
  sourceModelId: number,
  primaryStoreyId: StoreyId,
  risers: Riser[],
  aggregateRelationType: number,
  projectType: number,
): Set<number> {
  const lineIds = new Set<number>([primaryStoreyId, ...risers.map((riser) => riser.storeyId)])
  const aggregateRelationIds = api.GetLineIDsWithType(sourceModelId, aggregateRelationType)
  const relations: Array<{ id: number; relatingId: number | null; relatedIds: number[] }> = []

  for (let i = 0; i < aggregateRelationIds.size(); i++) {
    const relationId = aggregateRelationIds.get(i)
    const relation = api.GetLine(sourceModelId, relationId, false) as {
      RelatingObject?: IfcHandle | { expressID: number } | null
      RelatedObjects?: Array<IfcHandle | { expressID: number } | null> | null
    } | null

    if (!relation) continue

    relations.push({
      id: relationId,
      relatingId: toExpressId(relation.RelatingObject),
      relatedIds: Array.isArray(relation.RelatedObjects)
        ? relation.RelatedObjects
            .map((related) => toExpressId(related))
            .filter((relatedId): relatedId is number => relatedId !== null)
        : [],
    })
  }

  const pendingIds = [...lineIds]
  while (pendingIds.length > 0) {
    const currentId = pendingIds.pop()!
    for (const relation of relations) {
      if (!relation.relatedIds.includes(currentId)) continue
      lineIds.add(relation.id)
      for (const relatedId of relation.relatedIds) {
        lineIds.add(relatedId)
      }
      if (relation.relatingId !== null && !lineIds.has(relation.relatingId)) {
        lineIds.add(relation.relatingId)
        pendingIds.push(relation.relatingId)
      }
    }
  }

  const projectIds = api.GetLineIDsWithType(sourceModelId, projectType)
  for (let i = 0; i < projectIds.size(); i++) {
    lineIds.add(projectIds.get(i))
  }

  return lineIds
}

function collectRawLineClosure(
  api: IfcAPI,
  sourceModelId: number,
  seedLineIds: Set<number>,
): RawLineData[] {
  const rawLines = new Map<number, RawLineData>()
  const pendingIds = [...seedLineIds]

  while (pendingIds.length > 0) {
    const lineId = pendingIds.pop()!
    if (rawLines.has(lineId)) continue

    const rawLine = api.GetRawLineData(sourceModelId, lineId)
    if (!rawLine) continue
    rawLines.set(lineId, rawLine)

    for (const referencedId of collectReferencedExpressIds(rawLine.arguments)) {
      if (!rawLines.has(referencedId)) pendingIds.push(referencedId)
    }
  }

  return [...rawLines.values()].sort((left, right) => left.ID - right.ID)
}

function collectReferencedExpressIds(value: unknown): number[] {
  if (Array.isArray(value)) {
    return value.flatMap((item) => collectReferencedExpressIds(item))
  }

  if (!value || typeof value !== 'object') return []

  if ('type' in value && 'value' in value) {
    const typedValue = value as { type: number; value: unknown }
    if (typedValue.type === 5 && typeof typedValue.value === 'number') {
      return [typedValue.value]
    }
    return collectReferencedExpressIds(typedValue.value)
  }

  return Object.values(value).flatMap((item) => collectReferencedExpressIds(item))
}

function findStoreyContainmentRelation(
  api: IfcAPI,
  modelId: number,
  relationType: number,
  storeyId: StoreyId,
): {
  expressID: number
  type: number
  RelatedElements?: unknown[]
  RelatingStructure?: IfcHandle | null
} | null {
  const relationIds = api.GetLineIDsWithType(modelId, relationType)

  for (let i = 0; i < relationIds.size(); i++) {
    const relation = api.GetLine(modelId, relationIds.get(i), false) as {
      expressID: number
      type: number
      RelatedElements?: unknown[]
      RelatingStructure?: IfcHandle | null
    } | null

    const relatingId = relation?.RelatingStructure?.value ?? null
    if (relation && relatingId === storeyId) {
      return relation
    }
  }

  return null
}

function resolveCopiedOwnerHistoryHandle(
  api: IfcAPI,
  sourceModelId: number,
  targetModelId: number,
  primaryStoreyId: StoreyId,
): IfcHandle | null {
  const primaryStorey = api.GetLine(sourceModelId, primaryStoreyId, false) as {
    OwnerHistory?: IfcHandle | { expressID: number } | null
  } | null

  if (!primaryStorey) {
    throw new Error(`Storey #${primaryStoreyId} is missing from the IFC model.`)
  }

  const sourceOwnerHistory = toHandle(primaryStorey.OwnerHistory)
  if (!sourceOwnerHistory) return null

  try {
    const copiedOwnerHistory = api.GetLine(targetModelId, sourceOwnerHistory.value, false)
    if (!copiedOwnerHistory) return null
    return handleRef(sourceOwnerHistory.value)
  } catch {
    return null
  }
}

function toHandle(value: IfcHandle | { expressID: number } | null | undefined): IfcHandle | null {
  if (!value) return null
  if ('type' in value && value.type === 5 && typeof value.value === 'number') {
    return handleRef(value.value)
  }
  if ('expressID' in value && typeof value.expressID === 'number') return handleRef(value.expressID)
  return null
}

function toExpressId(value: IfcHandle | { expressID: number } | null | undefined): number | null {
  if (!value) return null
  if ('type' in value && value.type === 5 && typeof value.value === 'number') return value.value
  if ('expressID' in value && typeof value.expressID === 'number') return value.expressID
  return null
}

function handleRef(expressId: number): IfcHandle {
  return { type: 5, value: expressId }
}
